"""Provides indirect typing support for MDAnalysis, a library for
the analysis of molecular dynamics simulations. Despite the absence of inherent
typing support in MDAnalysis, the `mdanalysis.py` module uses Protocols to define
interfaces that allow type hinting for MDAnalysis objects.

While currently essential, this module is projected to become obsolete as soon
as the MDAnalysis library incorporates typing natively, eliminating the need for
indirect typing.

Classes:
    ResidueGroupType(Protocol): Provides a typing interface for MDAnalysis ResidueGroup objects.
    AtomGroupType(Protocol): Provides a typing interface for MDAnalysis AtomGroup objects.
    UniverseType(Protocol): Provides a typing interface for MDAnalysis Universe objects.

Example:
    def compute_distance(group: AtomGroupType) -> float:
        # An example function that operates on an mda.AtomGroup object.
        # The AtomGroupType Protocol allows type hinting for the group parameter.
        ...

    universe: UniverseType = ...
    atoms = universe.atoms
    compute_distance(atoms)

"""

from typing import Any, Optional, Protocol

import numpy as np
from numpy.typing import NDArray


class ResidueGroupType(Protocol):
    """A typing interface for MDAnalysis ResidueGroup objects."""

    @property
    def atoms(self) -> "AtomGroupType": ...

    @property
    def resnames(self) -> NDArray[np.str_]: ...

    @property
    def resids(self) -> NDArray[np.int32]: ...

    @property
    def resindices(self) -> NDArray[np.int_]: ...

    @property
    def n_residues(self) -> int: ...

    @property
    def segindices(self) -> NDArray[np.int_]: ...

    def __iter__(self) -> Any: ...

    def __add__(self, other: "ResidueGroupType") -> "ResidueGroupType": ...


class AtomGroupType(Protocol):
    """A typing interface for MDAnalysis AtomGroup objects."""

    def select_atoms(self, selection: str) -> "AtomGroupType": ...

    @property
    def file_name(self) -> str: ...

    @property
    def residues(self) -> "ResidueGroupType": ...

    @property
    def atoms(self) -> "AtomGroupType": ...

    @property
    def indices(self) -> NDArray[np.int32]: ...

    @property
    def positions(self) -> NDArray[np.float32]: ...

    @positions.setter
    def positions(self, positions: NDArray[np.float32]) -> None: ...

    @property
    def universe(self) -> "UniverseType": ...

    @property
    def n_atoms(self) -> int: ...

    @property
    def n_residues(self) -> int: ...

    @property
    def n_segments(self) -> int: ...

    @property
    def names(self) -> NDArray[np.str_]: ...

    @property
    def ids(self) -> NDArray[np.int32]: ...

    @property
    def ix(self) -> NDArray[np.int32]: ...

    @property
    def elements(self) -> NDArray[np.str_]: ...

    @property
    def types(self) -> NDArray[np.str_]: ...

    @property
    def resnames(self) -> NDArray[np.str_]: ...

    @property
    def resname(self) -> NDArray[np.str_]: ...

    @property
    def resids(self) -> NDArray[np.int32]: ...

    @property
    def resindices(self) -> NDArray[np.int_]: ...

    @property
    def chainIDs(self) -> NDArray[np.int32]: ...

    @property
    def vdw_radii(self) -> NDArray[np.float16]: ...

    @property
    def tempfactors(self) -> NDArray[np.float16]: ...

    def copy(self) -> "AtomGroupType": ...

    @property
    def _u(self) -> "UniverseType": ...

    @_u.setter
    def _u(self, universe: "UniverseType") -> None: ...

    def __iter__(self) -> Any: ...

    def __new__(cls, *args: Any, **kwargs: Any) -> "AtomGroupType": ...

    def __getitem__(self, index: int | slice | NDArray[np.int32] | NDArray[np.bool_]) -> "AtomGroupType": ...

    def __len__(self) -> int: ...

    def __add__(self, other: "AtomGroupType") -> "AtomGroupType": ...

    def __sub__(self, other: "AtomGroupType") -> "AtomGroupType": ...


class UniverseType(Protocol):
    """A typing interface for MDAnalysis Universe objects."""

    @property
    def atoms(self) -> "AtomGroupType": ...

    @property
    def universe(self) -> "UniverseType": ...

    @property
    def dimensions(self) -> Optional[NDArray[np.float32]]: ...

    @property
    def trajectory(self) -> "TrajectoryType": ...

    @property
    def _topology(self) -> Any: ...

    def select_atoms(self, selection: str) -> "AtomGroupType": ...

    def copy(self) -> "UniverseType": ...

    def add_TopologyAttr(self, name: str, attr: Any) -> None: ...

    def load_new(self, filenames: tuple[str, ...], **kwargs: Any) -> None: ...

    @property
    def filename(self) -> str: ...

    @filename.setter
    def filename(self, filename: str) -> None: ...

    def __iter__(self) -> Any: ...

    def __new__(cls, *args: Any, **kwargs: Any) -> "UniverseType": ...


class TrajectoryType(Protocol):
    @property
    def n_frames(self) -> int: ...

    def __getitem__(self, index: int | slice | NDArray[np.int32]) -> "TimeStepType": ...

    def __iter__(self) -> "TimeStepType": ...


class TimeStepType(Protocol):
    @property
    def frame(self) -> int: ...

    def __iter__(self) -> "TimeStepType": ...

    def __next__(self) -> "TimeStepType": ...
