[tool.black]
color = true
line-length = 120
target-version = ['py310']
skip-string-normalization = true

[tool.pyright]
include = ["lahuta"]
exclude = ["lahuta/scripts", "lahuta/tests", "**/__pycache__", "cachedir"]
defineConstant = { DEBUG = true }
reportMissingImports = true
reportMissingTypeStubs = "none"

[build-system]
requires = ["setuptools", "wheel"]

[tool.pylint.basic]
good-names = [
    'i', 
    'j',
    'k',
    'df', 
    'ag',
    'uv', 
    'ns',
    'ix',
]

[tool.pylint.'MASTER']
  extension-pkg-allow-list = ["gemmi"]

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 120

[tool.mypy]
python_version = 3.10
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
warn_no_return = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = false
disallow_untyped_defs = true
disallow_untyped_calls = true
strict_optional = true
no_implicit_optional = true
strict_equality = true
strict = true

[tool.pytest.ini_options]
testpaths = ["lahuta"]
filterwarnings = [
    "ignore::RuntimeWarning:lahuta.contacts.sulphur_pi",
    "ignore::RuntimeWarning:lahuta.contacts.carbon_pi",
    "ignore::RuntimeWarning:lahuta.contacts.cation_pi",
    "ignore::RuntimeWarning:lahuta.contacts.donor_pi",
]
