"""
Placeholder for the universe module.
"""

import lahuta.contacts as F
from lahuta.config.defaults import CONTACTS

from .base import ContactAnalysis


class AromaticContacts(ContactAnalysis):
    """A class to compute aromatic contacts.

    Parameters
    ----------
    ns : NeighborPairs
        The neighbor pairs object. This is usually generated by calling
        `compute_neighbors` on the Lahuta Universe object.

    """

    distance = CONTACTS["aromatic"]["distance"]

    def compute(self):
        """Compute aromatic contacts."""
        return F.aromatic_neighbors(self.ns, self.distance)
