"""
Module: aromatic.py

This module defines a class for computing aromatic contacts using a class-based approach. 
The AromaticContacts class inherits from the base ContactAnalysis class and 
implements the `compute` method for aromatic contact computation.

Class:
    AromaticContacts(ContactAnalysis): Computes aromatic contacts.
                                       
Example:
    universe = Universe(...)
    ns = universe.compute_neighbors()

    ac = AromaticContacts(ns)
    print(ac.results)
"""

import lahuta.contacts as F
from lahuta.config.defaults import CONTACTS
from lahuta.core.neighbors import NeighborPairs

from .base import ContactAnalysis


class AromaticContacts(ContactAnalysis):
    """A class to compute aromatic contacts.

    Parameters
    ----------
    ns : NeighborPairs
        The neighbor pairs object. This is usually generated by calling
        `compute_neighbors` on the Lahuta Universe object.

    """

    distance = CONTACTS["aromatic"]["distance"]

    def compute(self) -> NeighborPairs:
        """Compute aromatic contacts."""
        return F.aromatic_neighbors(self.ns, self.distance)
