"""
Placeholder for the universe module.
"""

from typing import Union

import MDAnalysis as mda
import numpy as np

from lahuta.config.defaults import CONTACTS

from ..core.neighbors import NeighborPairs
from ..core.universe import Universe
from .base import ContactAnalysis
from .protocol import ContactBase


class AromaticContacts_(ContactBase):
    """A class to compute aromatic contacts.

    Parameters
    ----------
    ua : Universe or AtomGroup
        Provide either a Universe or AtomGroup object.
    neighbors : NeighborPairs
        The neighbor pairs object. This is usually generated by calling
        `compute_neighbors` on a Universe  or AtomGroup object.

    """

    distance = CONTACTS["aromatic"]["distance"]

    # def __init__(self, ua: Union[Universe, mda.AtomGroup], neighbors: NeighborPairs):
    #     super().__init__(ua, neighbors)

    def compute_contacts(self, **kwargs) -> np.ndarray:
        """Get the aromatic contacts.

        Parameters
        ----------
        kwargs : dict
            The keyword arguments to pass to the `compute_contacts` method. None implemented yet.

        Returns
        -------
        np.ndarray
            The aromatic contacts between atoms in a molecule.

        """

        return (
            self.neighbors.type_filter("aromatic", 1)
            .type_filter("aromatic", 2)
            .distance_filter(self.distance)
            .pairs
        )


class AromaticContacts(ContactAnalysis):
    distance = CONTACTS["aromatic"]["distance"]

    def _compute(self, *_):
        return (
            self.ns.type_filter("aromatic", 1)
            .type_filter("aromatic", 2)
            .distance_filter(self.distance)
        )
