"""
Module: carbon_pi.py

This module provides class-level API for computing carbon-pi contacts, based on atom-plane interactions. 

Warning: 
    Due to re-computation, using the `CarbonPi` class may result in slower performance. 
    We recommend using the `AtomPlaneContacts` class from the `atom_plane` module for 
    improved efficiency. 

Classes:
    CarbonPi: A class to compute carbon-pi contacts. When instantiated, a warning about 
    potential performance issues is emitted.

Usage:
    universe = Universe(...)
    ns = universe.compute_neighbors()
    carbon_pi = CarbonPi(ns)
    results = carbon_pi.compute().results
"""

from warnings import warn

from lahuta.core.neighbors import NeighborPairs

from .atom_plane import DEFAULT_CONTACT_DISTS, carbon_pi
from .base import ContactAnalysis


class CarbonPi(ContactAnalysis):
    """
    Handles the computation of carbon pi contacts in a molecular system.

    Carbon pi contacts are interactions involving the π system of carbon atoms in a molecule.
    This class, a derivative of the `ContactAnalysis` base class, overrides the `compute`
    method to provide functionality specifically for carbon pi contact computation.

    Carbon-pi contacts represent interactions between a carbon atom and an aromatic ring system.
    These contacts arise due to the partial positive charge on the carbon atom interacting with the electron-rich
    π-system of the aromatic ring.

    We calculate carbon-pi contacts based on the following criteria:
    1. The interaction is between an aromatic ring and a carbon atom which is a weak hydrogen bond donor.
    2. The angle between the aromatic ring plane and the vector connecting the center of the aromatic ring
      and the carbon atom is within a specified cutoff.
    3. The distance between the carbon atom and the aromatic ring system does not exceed a predefined distance cutoff.

    Attributes:
        ns (NeighborPairs): The object encapsulating pairs of neighboring atoms in the system.
            This object is usually generated by calling the `compute_neighbors` method on the Lahuta Universe object.
        distance (float): The maximum distance to consider for a carbon pi contact. This value is retrieved
            from the 'carbon_pi' entry of the global DEFAULT_CONTACT_DISTS dictionary.
        cache (bool): Determines whether computed results should be stored for later use to improve performance.
            Set to `False` by default, meaning results will not be cached.

    Methods:
        compute() -> NeighborPairs: Computes and returns the carbon pi contacts, utilizing the `carbon_pi` function.
            The computation is based on the `ns` attribute, the class-specific `distance`, and the `cache` attribute.
    """

    distance = DEFAULT_CONTACT_DISTS["carbon_pi"]
    cache = False

    def __init__(self, ns: NeighborPairs):
        super().__init__(ns)
        warn(
            "Using the `CarbonPi` class may result in slower performance due to "
            "re-computation. Consider using the `AtomPlaneContacts` class from the "
            "`atom_plane` module for improved efficiency.",
            RuntimeWarning,
        )

    def compute(self) -> NeighborPairs:
        """Computes carbon pi contacts based on the neighbor pairs.

        Returns:
            NeighborPairs: A NeighborPairs object containing only carbon pi contacts.
        """
        return carbon_pi(self.ns, cache=self.cache)
