"""
Placeholder for the universe module.
"""

from typing import Union

import numpy as np

from ..core.groups import AtomGroup
from ..core.universe import Universe
from ..core.neighbors import NeighborPairsBase

from ..config import config

from .protocol import ContactBase


class CarbonylContacts(ContactBase):
    """A class to compute carbonyl contacts.

    Parameters
    ----------
    ua : Universe or AtomGroup
        Provide either a Universe or AtomGroup object.
    neighbors : NeighborPairsBase
        The neighbor pairs object. This is usually generated by calling
        `compute_neighbors` on a Universe  or AtomGroup object.

    """

    distance = config.CONTACT_TYPES["carbonyl"]["distance"]

    def __init__(self, ua: Union[Universe, AtomGroup], neighbors: NeighborPairsBase):
        # TODO:
        # put this into the config
        metals = config.METALS
        metals.add("Fe")

        print("metal indices")
        self.metal_indices = (
            ua.atoms[neighbors.indices]
            .select_atoms("element " + " ".join(metals))
            .indices
        )

        super().__init__(ua, neighbors)

    def compute_contacts(self, **kwargs) -> np.ndarray:
        """Get the carbonyl contacts.

        Parameters
        ----------
        kwargs : dict
            The keyword arguments to pass to the `compute_contacts` method. None implemented yet.

        Returns
        -------
        np.ndarray
            The carbonyl contacts between atoms in a molecule.

        """

        ionic_atom12 = (
            self.neighbors.type_filter("carbonyl oxygen", 0)
            .type_filter("carbonyl carbon", 1)
            .distance_filter(self.distance)
        )

        ionic_atom21 = (
            self.neighbors.type_filter("carbonyl carbon", 0)
            .type_filter("carbonyl oxygen", 1)
            .distance_filter(self.distance)
        )

        return np.concatenate((ionic_atom12.pairs, ionic_atom21.pairs), axis=0)
