"""
Placeholder for the universe module.
"""

import lahuta.contacts as F
from lahuta.config.defaults import CONTACTS

from .base import ContactAnalysis


class CarbonylContacts(ContactAnalysis):
    """A class to compute carbonyl contacts.

    Parameters
    ----------
    neighbors : NeighborPairs
        The neighbor pairs object. This is usually generated by calling
        `compute_neighbors` on the Lahuta Universe object.

    """

    distance = CONTACTS["carbonyl"]["distance"]

    def compute(self):
        """Compute carbonyl contacts."""
        return F.carbonyl_neighbors(self.ns, self.distance)
