"""Provides class-level API for computing cation-pi contacts, based on atom-plane interactions.

Warning:
    Due to re-computation, using the `CationPi` class may result in slower performance. 
    We recommend using the `AtomPlaneContacts` class from the `atom_plane` module for 
    improved efficiency. 

Classes:
    CationPi: A class to compute cation-pi contacts. When instantiated, a warning about 
    potential performance issues is emitted.

Usage:
    universe = Universe(...)
    ns = universe.compute_neighbors()
    cation_pi = CationPi(ns)
    results = cation_pi.compute().results

"""
import warnings

from lahuta.core.neighbors import NeighborPairs

from .atom_plane import DEFAULT_CONTACT_DISTS, cation_pi
from .base import ContactAnalysis


class CationPi(ContactAnalysis):
    """Handle the computation of cation pi contacts in a molecular system.

    Cation pi contacts are interactions between cations and the π system of atoms in a molecule.
    This class, a derivative of the `ContactAnalysis` base class, overrides the `compute`
    method to provide functionality specifically for cation pi contact computation.

    Cation-pi contacts involve interactions between a cation (a positively charged ion)
    and an electron-rich aromatic ring system. The aromatic system is capable of stabilizing the cation
    through its delocalized pi electrons.

    We calculate cation-pi contacts based on the following criteria:
    1. The interaction is between an aromatic ring and a positively ionizable atom.
    2. The angle between the aromatic ring plane and the vector connecting the center of the aromatic ring
      and the cation is within a defined cutoff.
    3. The distance between the cation and the aromatic ring system does not exceed a predefined distance cutoff.

    Attributes:
        ns (NeighborPairs): The object encapsulating pairs of neighboring atoms in the system.
            This object is usually generated by calling the `compute_neighbors` method on the Lahuta Universe object.
        distance (float): The maximum distance to consider for a cation pi contact. This value is retrieved
            from the 'cation_pi' entry of the global DEFAULT_CONTACT_DISTS dictionary.
        cache (bool): Determines whether computed results should be stored for later use to improve performance.
            set to `False` by default, meaning results will not be cached.

    Methods:
        compute() -> NeighborPairs: Computes and returns the cation pi contacts, utilizing the `cation_pi` function.
    """

    distance = DEFAULT_CONTACT_DISTS["cation_pi"]
    cache = False

    def __init__(self, ns: NeighborPairs):
        super().__init__(ns)
        warnings.warn(
            "Using the `CationPi` class may result in slower performance due to "
            "re-computation. Consider using the `AtomPlaneContacts` class from the "
            "`atom_plane` module for improved efficiency.",
            RuntimeWarning,
            stacklevel=2,
        )

    def compute(self) -> NeighborPairs:
        """Compute cation pi contacts based on the neighbor pairs.

        Returns:
            NeighborPairs: A NeighborPairs object containing only cation pi contacts.
        """
        return cation_pi(self.ns, cache=self.cache)
