"""
Placeholder for the universe module.
"""

from typing import Union

import numpy as np
from openbabel import openbabel as ob

from ..core.groups import AtomGroup
from ..core.neighbors import NeighborPairs
from ..core.universe import Universe
from .protocol import ContactBase


class CovalentContacts(ContactBase):
    """A class to compute covalent contacts between atoms in a molecule.

    Parameters
    ----------
    ua : Universe or AtomGroup
        Provide either a Universe or AtomGroup object.
    neighbors : NeighborPairs
        The neighbor pairs object. This is usually generated by calling
        `compute_neighbors` on a Universe  or AtomGroup object.

    """

    def __init__(self, ua: Union[Universe, AtomGroup], neighbors: NeighborPairs):
        super().__init__(ua, neighbors)

    def compute_contacts(self, **kwargs) -> np.ndarray:
        """Get the covalent contacts.

        Parameters
        ----------
        kwargs : dict
            The keyword arguments to pass to the `compute_contacts` method. None implemented yet.

        Returns
        -------
        np.ndarray
            The covalent contacts between atoms in a molecule.

        """

        cov_pair_indices = np.apply_along_axis(
            self.is_covalent, 1, self.neighbors.pairs
        )
        return self.neighbors.pairs[cov_pair_indices]

    def is_covalent(self, pair: np.ndarray):
        """Check if two atoms are bonded.

        Parameters
        ----------
        pair : np.ndarray
            An array of shape (2,) where each row is a pair of atom indices.

        Returns
        -------
        boolean: bool
            True if the pair is bonded, False otherwise.

        """
        ix1, ix2 = pair
        for cov_bonded in ob.OBAtomAtomIter(
            self._ua.atoms.universe.mol.GetAtom(int(ix1) + 1)
        ):
            if cov_bonded.GetId() == ix2:
                return True
        return False
