"""Provides class-level API for computing donor-pi contacts, based on atom-plane interactions.

Warning:
    Due to re-computation, using the `DonorPi` class may result in slower performance. 
    We recommend using the `AtomPlaneContacts` class from the `atom_plane` module for 
    improved efficiency. 

Classes:
    DonorPi: A class to compute donor-pi contacts. When instantiated, a warning about 
    potential performance issues is emitted.

Usage:
    universe = Universe(...)
    ns = universe.compute_neighbors()
    donor_pi = DonorPi(ns)
    results = donor_pi.compute().results

"""
import warnings

from lahuta.core.neighbors import NeighborPairs

from .atom_plane import DEFAULT_CONTACT_DISTS, donor_pi
from .base import ContactAnalysis


class DonorPi(ContactAnalysis):
    """Handle the computation of donor pi contacts in a molecular system.

    Donor pi contacts are interactions between electron donors and the π system of atoms in a molecule.
    This class, a derivative of the `ContactAnalysis` base class, overrides the `compute`
    method to provide functionality specifically for donor pi contact computation.

    Donor-pi contacts represent interactions between a hydrogen bond donor and an aromatic ring system.
    The electron-rich  aromatic ring can interact with the partial positive charge of a hydrogen atom
    that is involved in a polar bond, creating a stabilizing interaction.

    We computes donor-pi contacts based on the following criteria:
    1. The interaction is between an aromatic ring and a hydrogen bond donor.
    2. The angle between the aromatic ring plane and the vector connecting the center of the aromatic ring
      and the hydrogen bond donor is within a predefined cutoff.
    3. The distance between the hydrogen bond donor and the aromatic ring system does not exceed \
        a specified distance cutoff.

    Attributes:
        ns (NeighborPairs): The object encapsulating pairs of neighboring atoms in the system.
            This object is usually generated by calling the `compute_neighbors` method on the Lahuta Universe object.
        distance (float): The maximum distance to consider for a donor pi contact. This value is retrieved
            from the 'donor_pi' entry of the global DEFAULT_CONTACT_DISTS dictionary.
        cache (bool): Determines whether computed results should be stored for later use to improve performance.
            Set to `False` by default, meaning results will not be cached.

    Methods:
        compute() -> NeighborPairs: Computes and returns the donor pi contacts, utilizing the `donor_pi` function.
    """

    distance = DEFAULT_CONTACT_DISTS["donor_pi"]
    cache = False

    def __init__(self, ns: NeighborPairs):
        super().__init__(ns)
        warnings.warn(
            "Using the `DonorPi` class may result in slower performance due to "
            "re-computation. Consider using the `AtomPlaneContacts` class from the "
            "`atom_plane` module for improved efficiency.",
            RuntimeWarning,
            stacklevel=2,
        )

    def compute(self) -> NeighborPairs:
        """Compute donor pi contacts based on the neighbor pairs.

        Returns:
            NeighborPairs: A NeighborPairs object containing only donor pi contacts.
        """
        return donor_pi(self.ns, cache=self.cache)
