"""
Module: hbonds.py

This module defines a class for computing hbond-type contacts using a class-based approach. 
The HBondContacts class inherits from the base ContactAnalysis class and 
implements the `compute` method for hbond contact computation.

Class:
    HBondContacts(ContactAnalysis): Computes hbond contacts.
    WeakHBondContacts(ContactAnalysis): Computes weak hbond contacts.
    PolarHBondContacts(ContactAnalysis): Computes polar hbond contacts.
    WeakPolarHBondContacts(ContactAnalysis): Computes weak polar hbond contacts.
                                       
Example:
    universe = Universe(...)
    ns = universe.compute_neighbors()

    hbonds = HBondContacts(ns)
    print(hbonds.results)
"""

import lahuta.contacts as F
from lahuta.config.defaults import CONTACTS
from lahuta.core.neighbors import NeighborPairs

from .base import ContactAnalysis


class HBondContacts(ContactAnalysis):
    """
    Handles the computation of hydrogen bond (hbond) contacts in a molecular system.

    Hydrogen bonds are pivotal non-covalent interactions that significantly influence the structure, stability,
    and dynamics of biomolecules such as proteins and nucleic acids. A hydrogen bond forms when a hydrogen atom
    covalently bonded to a highly electronegative atom (such as oxygen or nitrogen) interacts with another
    electronegative atom from a different group.

    We compute hydrogen bonds based on the following criteria:
    1. It involves a hydrogen bond donor atom and a hydrogen bond acceptor atom.
    2. The distance between the hydrogen atom and the acceptor atom does not exceed a predefined cutoff distance.
    3. The angle formed by the donor, hydrogen, and acceptor atoms falls within a predefined range.
      This accounts for the directional nature of hydrogen bonds.

    Attributes:
        ns (NeighborPairs): The object encapsulating pairs of neighboring atoms in the system.
            This object is usually generated by calling the `compute_neighbors` method on the Lahuta Universe object.

    Methods:
        compute() -> NeighborPairs: Computes and returns the hbond contacts,
                    utilizing the `hbond_neighbors` function from module `F`.
    """

    def compute(self) -> NeighborPairs:
        """Computes hydrogen bond (hbond) contacts based on the neighbor pairs.

        Returns:
            NeighborPairs: A NeighborPairs object containing only hbond contacts.
        """
        return F.hbond_neighbors(self.ns)


class WeakHBondContacts(ContactAnalysis):
    """
    Handles the computation of weak hydrogen bond (weak hbond) contacts in a molecular system.

    Weak hydrogen bonds are a type of non-covalent interactions that, despite their reduced strength
    compared to regular hydrogen bonds, still play important roles in biomolecular structures and functions.
    These bonds form when a hydrogen atom, covalently linked to a weakly electronegative atom (such as carbon),
    interacts with an electronegative acceptor atom from a different group. The difference in electronegativity
    between the donor and acceptor atoms is what makes these bonds relatively weaker than conventional hydrogen bonds.

    We compute weak hydrogen bonds based on these considerations:
    1. A weak hydrogen bond involves a weak hydrogen bond donor atom and a hydrogen bond acceptor atom.
    2. The distance between the hydrogen atom and the acceptor atom does not surpass a certain cutoff distance.
    3. The angle formed by the donor, hydrogen, and acceptor atoms is within a predefined range.
      This accounts for the directional nature of hydrogen bonds.

    Attributes:
        ns (NeighborPairs): The object encapsulating pairs of neighboring atoms in the system.
            This object is usually generated by calling the `compute_neighbors` method on the Lahuta Universe object.

    Methods:
        compute() -> NeighborPairs: Computes and returns the weak hbond contacts,
                    utilizing the `weak_hbond_neighbors` function from module `F`.
    """

    def compute(self) -> NeighborPairs:
        """Computes weak hydrogen bond (weak hbond) contacts based on the neighbor pairs.

        Returns:
            NeighborPairs: A NeighborPairs object containing only weak hbond contacts.
        """
        return F.weak_hbond_neighbors(self.ns)


class PolarHBondContacts(ContactAnalysis):
    """
    Handles the computation of polar hydrogen bond (polar hbond) contacts in a molecular system.

    Polar hydrogen bonds involve a hydrogen atom covalently bonded to a polar atom (hydrogen bond donor),
    forming an interaction with another polar atom from a different group (hydrogen bond acceptor). In contrast to
    conventional hydrogen bonds, for polar hydrogen bonds, we do not consider the angle formed by the donor, hydrogen,
    and acceptor atoms.

    We compute polar hydrogen bonds based on these criteria:
    1. The presence of a hydrogen bond donor and a hydrogen bond acceptor.
    2. The distance between the hydrogen bond donor and the hydrogen bond acceptor does not exceed a specific cutoff distance.

    Attributes:
        ns (NeighborPairs): The object encapsulating pairs of neighboring atoms in the system.
            This object is usually generated by calling the `compute_neighbors` method on the Lahuta Universe object.
        distance (float): The maximum distance to consider for a polar hbond contact. This value is retrieved
            from the 'polar distance' entry of the 'hbond' section in the global CONTACTS dictionary.

    Methods:
        compute() -> NeighborPairs: Computes and returns the polar hbond contacts,
                    utilizing the `polar_hbond_neighbors` function from module `F`.
    """

    distance = CONTACTS["hbond"]["polar distance"]

    def compute(self) -> NeighborPairs:
        """Computes polar hydrogen bond (polar hbond) contacts based on the neighbor pairs and the set distance.

        Returns:
            NeighborPairs: A NeighborPairs object containing only polar hbond contacts.
        """
        return F.polar_hbond_neighbors(self.ns, self.distance)


class WeakPolarHBondContacts(ContactAnalysis):
    """
    Handles the computation of weak polar hydrogen bond (weak polar hbond) contacts in a molecular system.

    Weak polar hydrogen bonds rely on a weak hydrogen bond donor, and we also do not consider the angle
    formed by the donor, hydrogen, and acceptor atoms.

    We compute weak polar hydrogen bonds based on these criteria:
    1. The presence of a hydrogen bond acceptor and a weak hydrogen bond donor.
    2. The distance between the hydrogen bond acceptor and the weak hydrogen bond donor should not exceed a certain cutoff distance.

    Attributes:
        ns (NeighborPairs): The object encapsulating pairs of neighboring atoms in the system.
            This object is usually generated by calling the `compute_neighbors` method on the Lahuta Universe object.
        distance (float): The maximum distance to consider for a weak polar hbond contact. This value is retrieved
            from the 'weak polar distance' entry of the 'weak hbond' section in the global CONTACTS dictionary.

    Methods:
        compute() -> NeighborPairs: Computes and returns the weak polar hbond contacts,
                    utilizing the `weak_polar_hbond_neighbors` function from module `F`.
    """

    distance = CONTACTS["weak hbond"]["weak polar distance"]

    def compute(self) -> NeighborPairs:
        """Computes weak polar hydrogen bond (weak polar hbond) contacts based on the neighbor pairs and the set distance.

        Returns:
            NeighborPairs: A NeighborPairs object containing only weak polar hbond contacts.
        """
        return F.weak_polar_hbond_neighbors(self.ns, self.distance)
