"""
Placeholder for the universe module.
"""

from typing import Union

import MDAnalysis as mda
import numpy as np

from lahuta.config.defaults import CONTACTS

from ..core.neighbors import NeighborPairs
from ..core.universe import Universe
from .protocol import ContactBase


class HBondContacts(ContactBase):
    """A class to find hbond contacts between atoms in a molecule.

    Parameters
    ----------
    ua : Universe or AtomGroup
        Provide either a Universe or AtomGroup object.
    neighbors : NeighborPairs
        The neighbor pairs object. This is usually generated by calling
        `compute_neighbors` on a Universe  or AtomGroup object.

    """

    # def __init__(self, ua: Union[Universe, mda.AtomGroup], neighbors: NeighborPairs):
    #     super().__init__(ua, neighbors)

    def compute_contacts(self, **kwargs) -> np.ndarray:
        """Get the hbond contacts between atoms in a molecule.

        Parameters
        ----------
        kwargs : dict
            The keyword arguments to pass to the `compute_contacts` method. None implemented yet.

        Returns
        -------
        np.ndarray
            The hbond contacts between atoms in a molecule.

        """

        hbond_atom12 = (
            self.neighbors.type_filter("hbond_donor", 1)
            .type_filter("hbond_acceptor", 2)
            .hbond_distance_filter(partner=2)
            .hbond_angle_filter(partner=1)
        )

        hbond_atom21 = (
            self.neighbors.type_filter("hbond_donor", 2)
            .type_filter("hbond_acceptor", 1)
            .hbond_distance_filter(partner=1)
            .hbond_angle_filter(partner=2)
        )

        return np.unique(np.vstack((hbond_atom12.pairs, hbond_atom21.pairs)), axis=0)


class WeakHBondContacts(ContactBase):
    """A class to find weak hbond contacts between atoms in a molecule.

    Parameters
    ----------
    ua : Universe or AtomGroup
        Provide either a Universe or AtomGroup object.
    neighbors : NeighborPairs
        The neighbor pairs object. This is usually generated by calling
        `compute_neighbors` on a Universe  or AtomGroup object.

    """

    # def __init__(self, ua: Union[Universe, mda.AtomGroup], neighbors: NeighborPairs):
    #     super().__init__(ua, neighbors)

    def compute_contacts(self, **kwargs) -> np.ndarray:
        """Get the weak hbond contacts between atoms in a molecule.

        Parameters
        ----------
        kwargs : dict
            The keyword arguments to pass to the `compute_contacts` method. None implemented yet.

        Returns
        -------
        np.ndarray
            The hbond contacts between atoms in a molecule.

        """

        hbond_atom12 = (
            self.neighbors.type_filter("hbond_acceptor", 1)
            .type_filter("weak_hbond_donor", 2)
            .hbond_distance_filter(partner=1)
            .hbond_angle_filter(partner=2, weak=True)
        )

        hbond_atom21 = (
            self.neighbors.type_filter("hbond_acceptor", 2)
            .type_filter("weak_hbond_donor", 1)
            .hbond_distance_filter(partner=2)
            .hbond_angle_filter(partner=1, weak=True)
        )

        return np.unique(np.vstack((hbond_atom12.pairs, hbond_atom21.pairs)), axis=0)


class PolarHBondContacts(ContactBase):
    """A class to find polar hbond contacts between atoms in a molecule.

    Parameters
    ----------
    ua : Universe or AtomGroup
        Provide either a Universe or AtomGroup object.
    neighbors : NeighborPairs
        The neighbor pairs object. This is usually generated by calling
        `compute_neighbors` on a Universe  or AtomGroup object.

    """

    distance = CONTACTS["hbond"]["polar distance"]

    # def __init__(self, ua: Union[Universe, mda.AtomGroup], neighbors: NeighborPairs):
    #     super().__init__(ua, neighbors)

    def compute_contacts(self, **kwargs) -> np.ndarray:
        """Get the polar hbond contacts between atoms in a molecule.

        Parameters
        ----------
        kwargs : dict
            The keyword arguments to pass to the `compute_contacts` method. None implemented yet.

        Returns
        -------
        np.ndarray
            The polar hbond contacts between atoms in a molecule.

        """

        hbond_atom12 = (
            self.neighbors.type_filter("hbond_donor", 1)
            .type_filter("hbond_acceptor", 2)
            .distance_filter(self.distance)
        )

        hbond_atom21 = (
            self.neighbors.type_filter("hbond_donor", 2)
            .type_filter("hbond_acceptor", 1)
            .distance_filter(self.distance)
        )

        return np.unique(np.vstack((hbond_atom12.pairs, hbond_atom21.pairs)), axis=0)


class WeakPolarHBondContacts(ContactBase):
    """A class to find weak polar hbond contacts between atoms in a molecule.

    Parameters
    ----------
    ua : Universe or AtomGroup
        Provide either a Universe or AtomGroup object.
    neighbors : NeighborPairs
        The neighbor pairs object. This is usually generated by calling
        `compute_neighbors` on a Universe  or AtomGroup object.

    """

    distance = CONTACTS["weak hbond"]["weak polar distance"]

    # def __init__(self, ua: Union[Universe, mda.AtomGroup], neighbors: NeighborPairs):
    #     super().__init__(ua, neighbors)

    def compute_contacts(self, **kwargs) -> np.ndarray:
        """Get the weak polar hbond contacts between atoms in a molecule.

        Parameters
        ----------
        kwargs : dict
            The keyword arguments to pass to the `compute_contacts` method. None implemented yet.

        Returns
        -------
        np.ndarray
            The hbond contacts between atoms in a molecule.

        """

        hbond_atom12 = (
            self.neighbors.type_filter("hbond_acceptor", 1)
            .type_filter("weak_hbond_donor", 2)
            .distance_filter(self.distance)
        )

        hbond_atom21 = (
            self.neighbors.type_filter("hbond_acceptor", 2)
            .type_filter("weak_hbond_donor", 1)
            .distance_filter(self.distance)
        )

        return np.unique(np.vstack((hbond_atom12.pairs, hbond_atom21.pairs)), axis=0)
