"""
Placeholder for the universe module.
"""

from typing import Union

import numpy as np

from ..core.groups import AtomGroup
from ..core.universe import Universe
from ..core.neighbors import NeighborPairsBase

from .protocol import ContactBase


class HBondContacts(ContactBase):
    """A class to find weak hbond contacts between atoms in a molecule.

    Parameters
    ----------
    ua : Universe or AtomGroup
        Provide either a Universe or AtomGroup object.
    neighbors : NeighborPairsBase
        The neighbor pairs object. This is usually generated by calling
        `compute_neighbors` on a Universe  or AtomGroup object.

    """

    def __init__(self, ua: Union[Universe, AtomGroup], neighbors: NeighborPairsBase):
        super().__init__(ua, neighbors)

    def compute_contacts(self, **kwargs) -> np.ndarray:
        """Get the weak hbond contacts between atoms in a molecule.

        Parameters
        ----------
        kwargs : dict
            The keyword arguments to pass to the `compute_contacts` method. None implemented yet.

        Returns
        -------
        np.ndarray
            The weak hbond contacts between atoms in a molecule.

        """

        hbond_atom12 = (
            self.neighbors.type_filter("hbond donor", 0)
            .type_filter("hbond acceptor", 1)
            .contact_type("hbond")
            .hbond_distance_filter(col=1)
            .hbond_angle_filter(col=0)
        )

        hbond_atom21 = (
            self.neighbors.type_filter("hbond donor", 1)
            .type_filter("hbond acceptor", 0)
            .contact_type("hbond")
            .hbond_distance_filter(col=0)
            .hbond_angle_filter(col=1)
        )

        return np.concatenate((hbond_atom12.pairs, hbond_atom21.pairs), axis=0)
