"""
Placeholder for the universe module.
"""

from typing import Union

import numpy as np

from ..core.groups import AtomGroup
from ..core.universe import Universe
from ..core.neighbors import NeighborPairsBase

from lahuta.config.defaults import CONTACTS

from .protocol import ContactBase


class HydrophobicContacts(ContactBase):
    """A class to compute hydrophobic contacts.

    Parameters
    ----------
    ua : Universe or AtomGroup
        Provide either a Universe or AtomGroup object.
    neighbors : NeighborPairsBase
        The neighbor pairs object. This is usually generated by calling
        `compute_neighbors` on a Universe  or AtomGroup object.

    """

    distance = CONTACTS["hydrophobic"]["distance"]

    def __init__(self, ua: Union[Universe, AtomGroup], neighbors: NeighborPairsBase):
        super().__init__(ua, neighbors)

    def compute_contacts(self, **kwargs) -> np.ndarray:
        """Get the hydrophobic contacts.

        Parameters
        ----------
        kwargs : dict
            The keyword arguments to pass to the `compute_contacts` method. None implemented yet.

        Returns
        -------
        np.ndarray
            The hydrophobic contacts between atoms in a molecule.

        """

        return (
            self.neighbors.type_filter("hydrophobe", 0)
            .type_filter("hydrophobe", 1)
            .distance_filter(self.distance)
            .pairs
        )
