"""
Placeholder for the universe module.
"""

from typing import Union

import MDAnalysis as mda
import numpy as np

from lahuta.config.defaults import CONTACTS

from ..core.neighbors import NeighborPairs
from ..core.universe import Universe
from .protocol import ContactBase


class IonicContacts(ContactBase):
    """A class to find ionic contacts between atoms in a molecule.

    Parameters
    ----------
    ua : Universe or AtomGroup
        Provide either a Universe or AtomGroup object.
    neighbors : NeighborPairs
        The neighbor pairs object. This is usually generated by calling
        `compute_neighbors` on a Universe  or AtomGroup object.

    """

    distance = CONTACTS["ionic"]["distance"]

    # def __init__(self, ua: Union[Universe, mda.AtomGroup], neighbors: NeighborPairs):
    #     super().__init__(ua, neighbors)

    def compute_contacts(self, **kwargs) -> np.ndarray:
        """Get the ionic contacts.

        Parameters
        ----------
        kwargs : dict
            The keyword arguments to pass to the `compute_contacts` method. None implemented yet.

        Returns
        -------
        np.ndarray
            The ionic contacts between atoms in a molecule.

        """

        ionic_atom12 = (
            self.neighbors.type_filter("pos_ionisable", 0)
            .type_filter("neg_ionisable", 1)
            .distance_filter(self.distance)
        )

        ionic_atom21 = (
            self.neighbors.type_filter("neg_ionisable", 0)
            .type_filter("pos_ionisable", 1)
            .distance_filter(self.distance)
        )

        return np.concatenate((ionic_atom12.pairs, ionic_atom21.pairs), axis=0)
