"""
Placeholder for the universe module.
"""

from typing import Union

import numpy as np

from ..core.groups import AtomGroup
from ..core.universe import Universe
from ..core.neighbors import NeighborPairsBase

from ..config.defaults import CONTACTS
from ..config.atoms import METALS

from .protocol import ContactBase


class MetalContacts(ContactBase):
    """A class to compute metal contacts.

    Parameters
    ----------
    ua : Universe or AtomGroup
        Provide either a Universe or AtomGroup object.
    neighbors : NeighborPairsBase
        The neighbor pairs object. This is usually generated by calling
        `compute_neighbors` on a Universe  or AtomGroup object.

    """

    distance = CONTACTS["metal"]["distance"]

    def __init__(self, ua: Union[Universe, AtomGroup], neighbors: NeighborPairsBase):

        self.metal_indices = (
            ua.atoms[neighbors.indices]
            .select_atoms("element " + " ".join(METALS))
            .indices
        )

        super().__init__(ua, neighbors)

    def compute_contacts(self, **kwargs) -> np.ndarray:
        """Get the metal contacts.

        Parameters
        ----------
        kwargs : dict
            The keyword arguments to pass to the `compute_contacts` method. None implemented yet.

        Returns
        -------
        np.ndarray
            The metal contacts between atoms in a molecule.

        """

        # (atom1 is hbond acceptor and atom2 is metal  OR
        #  atom2 is hbond acceptor and atom1 is metal) AND
        # distance between atom1 and atom2 is less than `distance`
        acceptor_metal = (
            self.neighbors.type_filter("hbond acceptor", 0)
            .index_filter(self.metal_indices, 1)
            .distance_filter(self.distance)
        ).pairs

        metal_acceptor = (
            self.neighbors.type_filter("hbond acceptor", 1)
            .index_filter(self.metal_indices, 0)
            .distance_filter(self.distance)
        ).pairs

        return np.vstack((acceptor_metal, metal_acceptor))
