"""Provides class-level API for computing sulphur-pi contacts, based on atom-plane interactions.

Warning:
    Due to re-computation, using the `SulphurPi` class may result in slower performance. 
    We recommend using the `AtomPlaneContacts` class from the `atom_plane` module for 
    improved efficiency. 

Classes:
    SulphurPi: A class to compute sulphur-pi contacts. When instantiated, a warning about 
    potential performance issues is emitted.

Usage:
    universe = Universe(...)
    ns = universe.compute_neighbors()
    sulphur_pi = SulphurPi(ns)
    results = sulphur_pi.compute().results

"""
import warnings

from lahuta.core.neighbors import NeighborPairs

from .atom_plane import DEFAULT_CONTACT_DISTS, sulphur_pi
from .base import ContactAnalysis


class SulphurPi(ContactAnalysis):
    """Handle the computation of sulphur pi contacts in a molecular system.

    Sulphur pi contacts are interactions involving the π system of sulphur atoms in a molecule.
    This class, a derivative of the `ContactAnalysis` base class, overrides the `compute`
    method to provide functionality specifically for sulphur pi contact computation.

    Sulphur-pi interactions involve the interaction between an aromatic ring and a sulphur atom.
    Sulphur, particularly from methionine residues (MET), can interact with the electron cloud of an aromatic ring,
    contributing to the stability and specificity of biomolecular structures.

    We compute sulphur-pi contacts based on the following criteria:
    1. The interaction is between an aromatic ring and a sulphur atom specifically in a methionine residue.
    2. The distance between the sulphur atom and the aromatic ring system does not exceed a predefined distance cutoff.

    Attributes:
        ns (NeighborPairs): The object encapsulating pairs of neighboring atoms in the system.
            This object is usually generated by calling the `compute_neighbors` method on the Lahuta Universe object.
        distance (float): The maximum distance to consider for a sulphur pi contact. This value is retrieved
            from the 'sulphur_pi' entry of the global DEFAULT_CONTACT_DISTS dictionary.
        cache (bool): Determines whether computed results should be stored for later use to improve performance.
            Set to `False` by default, meaning results will not be cached.

    Methods:
        compute() -> NeighborPairs: Computes and returns the sulphur pi contacts, utilizing the `sulphur_pi` function.
    """

    distance = DEFAULT_CONTACT_DISTS["sulphur_pi"]
    cache = False

    def __init__(self, ns: NeighborPairs):
        super().__init__(ns)
        warnings.warn(
            "Using the `SulphurPi` class may result in slower performance due to "
            "re-computation. Consider using the `AtomPlaneContacts` class from the "
            "`atom_plane` module for improved efficiency.",
            RuntimeWarning,
            stacklevel=2,
        )

    def compute(self) -> NeighborPairs:
        """Compute sulphur pi contacts based on the neighbor pairs.

        Returns:
            NeighborPairs: A NeighborPairs object containing only sulphur pi contacts.
        """
        return sulphur_pi(self.ns, cache=self.cache)
