"""
Placeholder for the universe module.
"""

from typing import Union

import numpy as np

from ..core.groups import AtomGroup
from ..core.universe import Universe
from ..core.neighbors import NeighborPairsBase

from lahuta.config.defaults import CONTACTS

from .protocol import ContactBase

from ..utils.array import non_matching_indices


class VanDerWaalsContacts(ContactBase):
    """A class to compute VdW contacts.

    Parameters
    ----------
    ua : Universe or AtomGroup
        Provide either a Universe or AtomGroup object.
    neighbors : NeighborPairsBase
        The neighbor pairs object. This is usually generated by calling
        `compute_neighbors` on a Universe  or AtomGroup object.

    """

    # TODO: this should be put in the config file
    vdw_comp_factor = 0.1

    def __init__(self, ua: Union[Universe, AtomGroup], neighbors: NeighborPairsBase):
        super().__init__(ua, neighbors)

    def compute_contacts(self, **kwargs) -> np.ndarray:
        """Get the VdW contacts.

        Parameters
        ----------
        kwargs : dict
            The keyword arguments to pass to the `compute_contacts` method. None implemented yet.

        Returns
        -------
        np.ndarray
            The VdW contacts between atoms in a molecule.

        """

        pairs = self.neighbors.pairs

        vdw_radii = (
            self._ua.atoms.vdw_radii[pairs[:, 0]]
            + self._ua.atoms.vdw_radii[pairs[:, 1]]
        )

        vdw_comp_pairs = pairs[
            self.neighbors.distances <= vdw_radii + self.vdw_comp_factor
        ]

        if not kwargs.get("remove_clashes", True):
            return vdw_comp_pairs

        vdw_clash_pairs = pairs[self.neighbors.distances < vdw_radii]
        no_clash_indices = non_matching_indices(vdw_comp_pairs, vdw_clash_pairs)

        return vdw_comp_pairs[no_clash_indices]
