import enum
from typing import Self, overload

from lahuta.lib._lahuta import LahutaSystem, NSResults_

# fmt: off

class InteractionType(enum.IntEnum):
    None_             = 0
    Any               = 1
    Hydrophobic       = 2
    HydrogenBond      = 3
    WeakHydrogenBond  = 4
    Ionic             = 5
    MetalCoordination = 6
    CationPi          = 7
    PiStackingP       = 8
    PiStackingT       = 9


class EntityType(enum.IntEnum):
    Atom  = 0
    Ring  = 1
    Group = 2


class EntityID:
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    # should I provide __eq__, __lt__, etc. ?


class Contact:
    index1: EntityID
    index2: EntityID
    distance: float
    type: InteractionType

    def __init__(self, index1: EntityID, index2: EntityID, distance: float, interaction_type: InteractionType = InteractionType.None_) -> None: ...

    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Contact) -> bool: ...
    def __gt__(self, other: Contact) -> bool: ...
    def __le__(self, other: Contact) -> bool: ...
    def __ge__(self, other: Contact) -> bool: ...

class InteractionOptions:
    def __init__(self, distance_cutoff: float = 5.0) -> None: ...
    hbond:       bool
    weak_hbond:  bool
    hydrophobic: bool
    ionic:       bool
    metalic:     bool
    cationpi:    bool
    pistacking:  bool
    halogen:     bool

    sort_globally:         bool
    sort_per_contact_type: bool


class Contacts:
    interactions: list[Contact]
    is_sorted: bool
    instance_name: str

    def __init__(self, luni: LahutaSystem | None = None) -> None: ...

    def set_luni(self, luni: LahutaSystem) -> None: ...
    def sort_interactions(self)  -> None: ...
    def sort_if_not_sorted(self) -> None: ...

    @staticmethod
    def prepare_input(lhs: Contacts, rhs: Contacts) -> tuple[Contacts, Contacts]: ...

    @overload
    def add(self, contacts: Contacts) -> None: ...
    @overload
    def add(self, interaction: Contact) -> None: ...
    @overload
    def add(self, index1: EntityID, index2: EntityID, distance: float, interaction_type: InteractionType) -> None: ...
    @overload
    def add(self, interactions: list[Contact]) -> None: ...

    @overload
    def add_many(self, results: NSResults_, entity_ids: list[EntityID], contact_type: InteractionType) -> None: ...
    @overload
    def add_many(self, results: NSResults_, lhs_ids: list[EntityID], rhs_ids: list[EntityID], contact_type: InteractionType) -> None: ...

    def size(self) -> int: ...
    def make_generic(self) -> None: ...
    def get_luni(self) -> LahutaSystem: ...
    def print(self) -> None: ...

    def __eq__  (self, other: object) -> bool: ...
    def __ne__  (self, other: object) -> bool: ...
    def __and__ (self, other: Contacts) -> Contacts: ...
    def __or__  (self, other: Contacts) -> Contacts: ...
    def __sub__ (self, other: Contacts) -> Contacts: ...
    def __xor__ (self, other: Contacts) -> Contacts: ...
    def __iand__(self, other: Contacts) -> Self: ...
    def __ior__ (self, other: Contacts) -> Self: ...
    def __isub__(self, other: Contacts) -> Self: ...
    def __ixor__(self, other: Contacts) -> Self: ...
    def __getitem__(self, index: int) -> Contact: ...


class Interactions:
    def __init__(self, luni: LahutaSystem, opts: InteractionOptions | None = None) -> None: ...
    def hbond(self)       -> Contacts: ...
    def weak_hbond(self)  -> Contacts: ...
    def hydrophobic(self) -> Contacts: ...
    def halogen(self)     -> Contacts: ...
    def ionic(self)       -> Contacts: ...
    def metalic(self)     -> Contacts: ...
    def cationpi(self)    -> Contacts: ...
    def pistacking(self)  -> Contacts: ...

    def compute_contacts(self) -> Contacts: ...
