import pytest
from _pytest.fixtures import FixtureRequest

from lahuta.analysis.dssp import DSSP, DSSPParser

from tests.test_data_loading import TEST_PARAMS


EXPECTED_DATA = {
    'x2': {
        'sasa': [
            108,
            114,
            66,
            180,
            81,
            13,
            84,
            44,
            17,
            43,
            89,
            136,
            16,
            37,
            42,
            100,
            48,
            31,
            73,
            159,
            29,
            84,
            79,
            73,
            17,
            38,
            102,
            27,
            156,
            54,
            101,
            71,
            36,
            2,
            121,
            74,
            101,
            76,
            86,
            179,
            20,
            41,
            74,
            65,
            28,
            4,
            117,
            48,
            29,
            99,
            106,
            20,
            94,
            163,
            85,
            49,
            61,
            101,
            12,
            14,
            122,
            27,
            137,
            142,
            23,
            63,
            72,
            148,
            33,
            19,
            73,
            28,
            4,
            9,
            113,
            92,
            39,
            45,
            119,
            0,
            22,
        ],
        'ss': [
            '-',
            '-',
            '-',
            'S',
            '-',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'S',
            'T',
            'T',
            'S',
            'S',
            'T',
            'T',
            'T',
            'T',
            'G',
            'G',
            'G',
            '-',
            '-',
            '-',
            'T',
            'T',
            '-',
            'S',
            'T',
            'T',
            'T',
            'H',
            'H',
            'H',
            'H',
            'T',
            'T',
            '-',
            'S',
            'T',
            'T',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'T',
            '-',
            'T',
            'T',
            'S',
            '-',
            'G',
            'G',
            'G',
            'G',
            '-',
            'S',
            'S',
            '-',
            '-',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'T',
            'S',
            '-',
            '-',
        ],
        'resinfo': [
            ('A', 'ALA', -3),
            ('A', 'ASP', -2),
            ('A', 'LEU', -1),
            ('A', 'GLN', 1),
            ('A', 'ASP', 2),
            ('A', 'ALA', 3),
            ('A', 'GLU', 4),
            ('A', 'ALA', 5),
            ('A', 'ILE', 6),
            ('A', 'TYR', 7),
            ('A', 'ASN', 8),
            ('A', 'LYS', 9),
            ('A', 'ALA', 10),
            ('A', 'CYS', 11),
            ('A', 'THR', 12),
        ],
    },
    'rhodopsin': {
        'sasa': [
            195,
            71,
            4,
            23,
            106,
            13,
            110,
            52,
            21,
            17,
            0,
            7,
            73,
            44,
            70,
            186,
            101,
            34,
            43,
            9,
            113,
            15,
            0,
            31,
            114,
            24,
            54,
            0,
            92,
            47,
            15,
            12,
            112,
            61,
            158,
            42,
            3,
            69,
            107,
            17,
            5,
            46,
            69,
            0,
            116,
            107,
            12,
            17,
            91,
            92,
            0,
            89,
            57,
            27,
            0,
            99,
            32,
            0,
            42,
            114,
            0,
            3,
            82,
            84,
            3,
            141,
            105,
            1,
            47,
            58,
            16,
            5,
            3,
            39,
            4,
            1,
            41,
            9,
            3,
            0,
            45,
            1,
            1,
            26,
            90,
            1,
            0,
            102,
            15,
            1,
            2,
            57,
            9,
            0,
            29,
            85,
            0,
            1,
            99,
            76,
        ],
        'ss': [
            '-',
            '-',
            'S',
            'E',
            'E',
            'E',
            'T',
            'T',
            'E',
            'E',
            'E',
            'S',
            'S',
            '-',
            '-',
            'T',
            'T',
            'S',
            '-',
            '-',
            '-',
            '-',
            'T',
            'T',
            'T',
            'S',
            '-',
            '-',
            'T',
            'T',
            'T',
            'S',
            '-',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            '-',
            'T',
            'T',
            '-',
            '-',
            'S',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'I',
            'I',
            'I',
            'I',
            'I',
            'I',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
        ],
        'resinfo': [
            ('A', 'MET', 1),
            ('A', 'ASN', 2),
            ('A', 'GLY', 3),
            ('A', 'THR', 4),
            ('A', 'GLU', 5),
            ('A', 'GLY', 6),
            ('A', 'PRO', 7),
            ('A', 'ASN', 8),
            ('A', 'PHE', 9),
            ('A', 'TYR', 10),
            ('A', 'VAL', 11),
            ('A', 'PRO', 12),
            ('A', 'PHE', 13),
            ('A', 'SER', 14),
            ('A', 'ASN', 15),
        ],
    },
    'dnabound': {
        'sasa': [
            206,
            195,
            89,
            102,
            51,
            35,
            28,
            31,
            94,
            0,
            25,
            88,
            101,
            8,
            149,
            17,
            61,
            58,
            161,
            19,
            0,
            102,
            135,
            18,
            21,
            76,
            28,
            93,
            6,
            9,
            100,
            13,
            60,
            95,
            64,
            32,
            105,
            147,
            70,
            79,
            144,
            68,
            63,
            0,
            34,
            82,
            91,
            21,
            35,
            108,
            112,
            1,
            91,
            40,
            2,
            80,
            59,
            0,
            128,
            208,
            65,
            53,
            9,
            71,
            33,
            117,
            84,
            2,
            77,
            140,
            2,
            67,
            141,
            60,
            67,
            151,
            147,
            53,
            37,
            156,
            48,
            35,
            93,
            62,
            75,
            22,
            104,
            126,
            74,
            82,
            137,
            53,
            136,
            99,
            118,
            133,
            98,
            84,
            52,
            53,
        ],
        'ss': [
            '-',
            '-',
            'S',
            '-',
            'E',
            'E',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'T',
            '-',
            '-',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'T',
            'T',
            'S',
            'S',
            '-',
            '-',
            'S',
            'E',
            'E',
            '-',
            'T',
            'T',
            'T',
            '-',
            '-',
            'E',
            'E',
            'E',
            '-',
            'S',
            'G',
            'G',
            'G',
            'G',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'T',
            '-',
            '-',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'T',
            'T',
            '-',
            '-',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
            'H',
        ],
        'resinfo': [
            ('A', 'LYS', 2),
            ('A', 'GLU', 3),
            ('A', 'SER', 4),
            ('A', 'TYR', 5),
            ('A', 'TYR', 6),
            ('A', 'SER', 7),
            ('A', 'ILE', 8),
            ('A', 'GLY', 9),
            ('A', 'GLU', 10),
            ('A', 'VAL', 11),
            ('A', 'SER', 12),
            ('A', 'LYS', 13),
            ('A', 'LEU', 14),
            ('A', 'ALA', 15),
            ('A', 'ASN', 16),
        ],
    },
}


@pytest.fixture(scope="session", params=TEST_PARAMS)
def data_loader(request: FixtureRequest) -> tuple[str, DSSP]:
    pdb_name, pdb_class, pdb_flag = request.param
    dssp = DSSP(pdb_class(pdb_flag).file_loc)
    dssp.parse_or_calculate_dssp()
    return pdb_name, dssp


def test_dssp_calculation(data_loader: tuple[str, DSSP]) -> None:
    _, dssp = data_loader

    # test non-zero size
    assert dssp.resinfo_array.shape[0] != 0
    assert dssp.ss_array.shape[0] != 0
    assert dssp.acc_array.shape[0] != 0

    # test equal size
    assert dssp.ss_array.shape[0] == dssp.resinfo_array.shape[0]
    assert dssp.acc_array.shape[0] == dssp.resinfo_array.shape[0]

    # test dtypes
    assert dssp.resinfo_array.dtype == DSSPParser.DTYPES
    assert dssp.ss_array.dtype == '<U1'
    assert dssp.acc_array.dtype == int


def test_dssp_results(data_loader: tuple[str, DSSP]) -> None:
    key, dssp = data_loader

    # test sasa
    assert dssp.acc_array.tolist()[:100] == EXPECTED_DATA[key]['sasa']

    # test secondary structure
    assert dssp.ss_array.tolist()[:100] == EXPECTED_DATA[key]['ss']

    # test resinfo
    assert dssp.resinfo_array.tolist()[:15] == EXPECTED_DATA[key]['resinfo']
