"""
# Module: config._atom_type_strings.py

This module provides string representations of various atom types and categories.

The various types of atoms represented here include metals, standard amino acids, 
different types of bond acceptors and donors, ionisable atoms, 
hydrophobic atoms, carbonyl atoms, and aromatic atoms.

The atom types are initially defined as comma-separated strings. 
These strings are then processed into sets for easy and efficient access 
throughout the rest of the library.

This file is licensed under [GNU General Public License](../path/to/license/file). 
For more details, see also the [GNU General Public License webpage](http://www.gnu.org/licenses/).
"""
# fmt: off
_METALS_STR = (
    "Li,Be,Na,Mg,Aa,K,Ca,Sc,Ti,V,Cr,Mn,Fe,Co,Ni,Cu,Zn,Ga,Rb,Sr,Y,Zr,Nb,Mo,"
    "Tc,Ru,Rh,Pd,Ag,Cd,In,Sn,Cs,Ba,La,Ce,Pr,Nd,Pm,Sm,Eu,Gd,Tb,Dy,Ho,Er,Tm,Yb,"
    "Lu,Hf,Ta,W,Re,Os,Ir,Pt,Au,Hg,Tl,Pb,Bi,Po,Fr,Ra,Ac,Th,Pa,U,Np,Pu,Am,Cm,Bk,Cf"
)

_STANDARD_AA_STR = "ALA,CYS,ASP,GLU,PHE,GLY,HIS,ILE,LYS,LEU,MET,ASN,PRO,GLN,ARG,SER,THR,VAL,TRP,TYR"

_HA_ATOM_TYPES = (
    "ALAO,ARGO,ASNO,ASPO,CYSO,GLNO,GLUO,GLYO,HISO,ILEO,LEUO,LYSO,METO,PHEO,PROO,"
    "SERO,THRO,TRPO,TYRO,VALO,ALAOXT,ARGOXT,ASNOXT,ASPOXT,CYSOXT,GLNOXT,GLUOXT,GLYOXT,"
    "HISOXT,ILEOXT,LEUOXT,LYSOXT,METOXT,PHEOXT,PROOXT,SEROXT,THROXT,TRPOXT,TYROXT,VALOXT,"
    "ASNOD1,ASNND2,ASPOD1,ASPOD2,GLNOE1,GLNNE2,GLUOE1,GLUOE2,HISND1,HISCE1,HISNE2,"
    "HISCD2,METSD,CYSSG,SEROG,THROG1,TYROH"
)

_HD_ATOM_TYPES = (
    "ALAN,ARGN,ASNN,ASPN,CYSN,GLNN,GLUN,GLYN,HISN,ILEN,LEUN,LYSN,METN,PHEN,"
    "SERN,THRN,TRPN,TYRN,VALN,ARGNE,ARGNH1,ARGNH2,ASNND2,ASNOD1,CYSSG,GLNNE2,"
    "GLNOE1,HISND1,HISCE1,HISNE2,HISCD2,LYSNZ,SEROG,THROG1,TRPNE1,TYROH"
)

_XA_ATOM_TYPES = (
    "ALAO,ARGO,ASNO,ASPO,CYSO,GLNO,GLUO,GLYO,HISO,ILEO,LEUO,LYSO,METO,PHEO,PROO,"
    "SERO,THRO,TRPO,TYRO,VALO,ALAOXT,ARGOXT,ASNOXT,ASPOXT,CYSOXT,GLNOXT,GLUOXT,"
    "GLYOXT,HISOXT,ILEOXT,LEUOXT,LYSOXT,METOXT,PHEOXT,PROOXT,SEROXT,THROXT,TRPOXT,"
    "TYROXT,VALOXT,ASNOD1,ASNND2,ASPOD1,ASPOD2,GLNOE1,GLNNE2,GLUOE1,GLUOE2,HISND1,"
    "HISCE1,HISNE2,HISCD2,METSD,CYSSG,SEROG,THROG1,TYROH"
)

_XD_ATOM_TYPES = ""

_WHA_ATOM_TYPES = (
    "ALAO,ARGO,ASNO,ASPO,CYSO,GLNO,GLUO,GLYO,HISO,ILEO,LEUO,LYSO,METO,PHEO,"
    "PROO,SERO,THRO,TRPO,TYRO,VALO,ALAOXT,ARGOXT,ASNOXT,ASPOXT,CYSOXT,GLNOXT,"
    "GLUOXT,GLYOXT,HISOXT,ILEOXT,LEUOXT,LYSOXT,METOXT,PHEOXT,PROOXT,SEROXT,THROXT,"
    "TRPOXT,TYROXT,VALOXT,ASNOD1,ASNND2,ASPOD1,ASPOD2,GLNOE1,GLNNE2,GLUOE1,GLUOE2,"
    "HISND1,HISCE1,HISNE2,HISCD2,METSD,CYSSG,SEROG,THROG1,TYROH"
)

_WHD_ATOM_TYPES = (
    "ALACA,ARGCA,ASNCA,ASPCA,CYSCA,GLNCA,GLUCA,GLYCA,HISCA,ILECA,LEUCA,LYSCA,"
    "METCA,PHECA,PROCA,SERCA,THRCA,TRPCA,TYRCA,VALCA,ALACB,ARGCB,ARGCG,ARGCD,"
    "ASNCB,ASPCB,CYSCB,GLNCB,GLNCG,GLUCB,GLUCG,GLNCB,HISCB,ILECB,ILECG1,ILECD1,"
    "ILECG2,LEUCB,LEUCG,LEUCD1,LEUCD2,LYSCB,LYSCG,LYSCD,LYSCE,METCB,METCG,METCE,"
    "PHECB,PHECG,PHECD1,PHECD2,PHECE1,PHECE2,PHECZ,PROCB,PROCG,PROCD,SERCB,"
    "THRCB,THRCG2,TRPCB,TRPCD1TRPCE3,TRPCZ3,TRPCH2,TRPCZ2,TYRCB,TYRCD1,TYRCD2,"
    "TYRCE1,TYRCE2,TRYCB,VALCB,VALCG1,VALCG2"
)

_POS_IONISABLE_ATOM_TYPES = "ARGNE,ARGCZ,ARGNH1,ARGNH2,HISCG,HISND1,HISCE1,HISNE2,HISCD2,LYSNZ"

_NEG_IONISABLE_ATOM_TYPES = "ASPOD1,ASPOD2,GLUOE1,GLUOE2"

_HYDROPHOBE_ATOM_TYPES = (
    "ALACB,ARGCB,ARGCG,ASNCB,ASPCB,CYSCB,GLNCB,GLNCG,GLUCB,GLUCG,GLNCB,HISCB,"
    "ILECB,ILECG1,ILECD1,ILECG2,LEUCB,LEUCG,LEUCD1,LEUCD2,LYSCB,LYSCG,LYSCD,"
    "METCB,METCG,METSD,METCE,PHECB,PHECG,PHECD1,PHECD2,PHECE1,PHECE2,PHECZ,PROCB,"
    "PROCG,THRCG2,TRPCB,TRPCG,TRPCD2,TRPCE3,TRPCZ3,TRPCH2,TRPCZ2,TRYCB,TYRCG,"
    "TYRCD1,TYRCD2,TYRCE1,TYRCE2,VALCB,VALCG1,VALCG2"
)

_CARBONYL_OXYGEN_ATOM_TYPES = (
    "ALAO,ARGO,ASNO,ASPO,CYSO,GLNO,GLUO,GLYO,HISO,ILEO,LEUO," 
    "LYSO,METO,PHEO,PROO,SERO,THRO,TRPO,TYRO,VALO"
)

_CARBONYL_CARBON_ATOM_TYPES = (
    "ALAC,ARGC,ASNC,ASPC,CYSC,GLNC,GLUC,GLYC,HISC,ILEC,LEUC,LYSC," 
    "METC,PHEC,PROC,SERC,THRC,TRPC,TYRC,VALC"
)

_AROMATIC_ATOM_TYPES = (
    "HISCG,HISND1,HISCE1,HISNE2,HISCD2,PHECG,PHECD1,PHECD2,PHECE1,PHECE2,PHECZ,"
    "TRPCG,TRPCD1,TRPCD2,TRPNE1,TRPCE2,TRPCE3,TRPCZ2,TRPCZ3,TRPCH2,TYRCG,TYRCD1,"
    "TYRCD2,TYRCE1,TYRCE2,TYRCZ"
)

# FIXME: update with the residue list provided by MDAnalysis
METALS = set(_METALS_STR.split(","))
STANDARD_AMINO_ACIDS = set(_STANDARD_AA_STR.split(","))
HBOND_ACCEPTORS = set(_HA_ATOM_TYPES.split(","))
HBOND_DONORS = set(_HD_ATOM_TYPES.split(","))
XBOND_ACCEPTORS = set(_XA_ATOM_TYPES.split(","))
XBOND_DONORS = set("")
WEAK_HBOND_ACCEPTORS = set(_WHA_ATOM_TYPES.split(","))
WEAK_HBOND_DONORS = set(_WHD_ATOM_TYPES.split(","))
POS_IONISABLE = set(_POS_IONISABLE_ATOM_TYPES.split(","))
NEG_IONISABLE = set(_NEG_IONISABLE_ATOM_TYPES.split(","))
HYDROPHOBES = set(_HYDROPHOBE_ATOM_TYPES.split(","))
CARBONYL_OXYGENS = set(_CARBONYL_OXYGEN_ATOM_TYPES.split(","))
CARBONYL_CARBONS = set(_CARBONYL_CARBON_ATOM_TYPES.split(","))
AROMATIC = set(_AROMATIC_ATOM_TYPES.split(","))

# NOTES
# "ALAO",    # all the carbonyl Oxygens in the main chain
# "ALAOXT",  # all the carbonyl Oxygens terminals
# "ASNND2",  # for the ambiguity of the position of the N and O
# "GLNOE1"   # for the ambiguity of the position of the N and O
# "GLNNE2",  # for the ambiguity of the position of the N and O
# "HISND1",  # for the ambiguity of the position of the N/C
# "HISCE1",  # for the ambiguity of the position of the N/C
# "HISNE2",  # for the ambiguity of the position of the N/C
# "HISCD2",  # for the ambiguity of the position of the N/C
# "METSD",   # http://pubs.acs.org/doi/abs/10.1021/jz300207k and pubid 19089987
# "CYSSG",   # pubid 19089987, also when they from di-sulfide (Cys-Cys, fig 8 paper)
# "SEROG",   # isostar plots
# "THROG1",  # isostar plots
# "TYROH",   # isostar plots
# "ALAN",    # all the amide nitrogens in the main chain except proline
# "ASNOD1",  # for the ambiguity of the position of the N and O
# "CYSSG",   # http://www.ncbi.nlm.nih.gov/pubmed/19089987
# "ALACA",   # all the c-alphas
# "ALACB",   # cb and further down
# "CYSCB",   # sulfur in Cys has an Hydrogen, it is polarised
