# NAMES
HALOGENS = set(["F", "CL", "BR", "I", "AT"])

MAINCHAIN_ATOMS = set(["N", "C", "CA", "O", "OXT"])

METALS = set(
    [
        "Li",
        "Be",
        "Na",
        "Mg",
        "Aa",
        "K",
        "Ca",
        "Sc",
        "Ti",
        "V",
        "Cr",
        "Mn",
        "Fe",
        "Co",
        "Ni",
        "Cu",
        "Zn",
        "Ga",
        "Rb",
        "Sr",
        "Y",
        "Zr",
        "Nb",
        "Mo",
        "Tc",
        "Ru",
        "Rh",
        "Pd",
        "Ag",
        "Cd",
        "In",
        "Sn",
        "Cs",
        "Ba",
        "La",
        "Ce",
        "Pr",
        "Nd",
        "Pm",
        "Sm",
        "Eu",
        "Gd",
        "Tb",
        "Dy",
        "Ho",
        "Er",
        "Tm",
        "Yb",
        "Lu",
        "Hf",
        "Ta",
        "W",
        "Re",
        "Os",
        "Ir",
        "Pt",
        "Au",
        "Hg",
        "Tl",
        "Pb",
        "Bi",
        "Po",
        "Fr",
        "Ra",
        "Ac",
        "Th",
        "Pa",
        "U",
        "Np",
        "Pu",
        "Am",
        "Cm",
        "Bk",
        "Cf",
    ]
)

# TYPES
PROT_ATOM_TYPES = {
    "hbond_acceptor": set(
        [
            "ALAO",  # all the carbonyl Oxygens in the main chain
            "ARGO",
            "ASNO",
            "ASPO",
            "CYSO",
            "GLNO",
            "GLUO",
            "GLYO",
            "HISO",
            "ILEO",
            "LEUO",
            "LYSO",
            "METO",
            "PHEO",
            "PROO",
            "SERO",
            "THRO",
            "TRPO",
            "TYRO",
            "VALO",
            "ALAOXT",  # all the carbonyl Oxygens terminals
            "ARGOXT",
            "ASNOXT",
            "ASPOXT",
            "CYSOXT",
            "GLNOXT",
            "GLUOXT",
            "GLYOXT",
            "HISOXT",
            "ILEOXT",
            "LEUOXT",
            "LYSOXT",
            "METOXT",
            "PHEOXT",
            "PROOXT",
            "SEROXT",
            "THROXT",
            "TRPOXT",
            "TYROXT",
            "VALOXT",
            "ASNOD1",
            "ASNND2",  # for the ambiguity of the position of the N and O
            "ASPOD1",
            "ASPOD2",
            "GLNOE1" "GLNNE2",  # for the ambiguity of the position of the N and O
            "GLUOE1",
            "GLUOE2",
            "HISND1",  # for the ambiguity of the position of the N/C
            "HISCE1",  # for the ambiguity of the position of the N/C
            "HISNE2",  # for the ambiguity of the position of the N/C
            "HISCD2",  # for the ambiguity of the position of the N/C
            "METSD",  # http://pubs.acs.org/doi/abs/10.1021/jz300207k and pubid 19089987
            "CYSSG",  # pubid 19089987, also when they from di-sulfide (Cys-Cys, fig 8 paper)
            "SEROG",  # isostar plots
            "THROG1",  # isostar plots
            "TYROH",  # isostar plots
        ]
    ),
    "hbond_donor": set(
        [
            "ALAN",  # all the amide nitrogens in the main chain except proline
            "ARGN",
            "ASNN",
            "ASPN",
            "CYSN",
            "GLNN",
            "GLUN",
            "GLYN",
            "HISN",
            "ILEN",
            "LEUN",
            "LYSN",
            "METN",
            "PHEN",
            "SERN",
            "THRN",
            "TRPN",
            "TYRN",
            "VALN",
            "ARGNE",
            "ARGNH1",
            "ARGNH2",
            "ASNND2",
            "ASNOD1",  # for the ambiguity of the position of the N and O
            "CYSSG",  # http://www.ncbi.nlm.nih.gov/pubmed/19089987
            "GLNNE2",
            "GLNOE1",  # for the ambiguity of the position of N/O
            "HISND1",  # for the ambiguity of the position of the N/C
            "HISCE1",  # for the ambiguity of the position of the N/C
            "HISNE2",  # for the ambiguity of the position of the N/C
            "HISCD2",  # for the ambiguity of the position of the N/C
            "LYSNZ",
            "SEROG",
            "THROG1",
            "TRPNE1",
            "TYROH",
        ]
    ),
    "xbond_acceptor": set(
        [
            "ALAO",  # all the carbonyl Oxygens in the main chain
            "ARGO",
            "ASNO",
            "ASPO",
            "CYSO",
            "GLNO",
            "GLUO",
            "GLYO",
            "HISO",
            "ILEO",
            "LEUO",
            "LYSO",
            "METO",
            "PHEO",
            "PROO",
            "SERO",
            "THRO",
            "TRPO",
            "TYRO",
            "VALO",
            "ALAOXT",  # all the carbonyl Oxygens terminals
            "ARGOXT",
            "ASNOXT",
            "ASPOXT",
            "CYSOXT",
            "GLNOXT",
            "GLUOXT",
            "GLYOXT",
            "HISOXT",
            "ILEOXT",
            "LEUOXT",
            "LYSOXT",
            "METOXT",
            "PHEOXT",
            "PROOXT",
            "SEROXT",
            "THROXT",
            "TRPOXT",
            "TYROXT",
            "VALOXT",
            "ASNOD1",
            "ASNND2",  # for the ambiguity of the position of the N and O
            "ASPOD1",
            "ASPOD2",
            "GLNOE1" "GLNNE2",  # for the ambiguity of the position of the N and O
            "GLUOE1",
            "GLUOE2",
            "HISND1",  # for the ambiguity of the position of the N/C
            "HISCE1",  # for the ambiguity of the position of the N/C
            "HISNE2",  # for the ambiguity of the position of the N/C
            "HISCD2",  # for the ambiguity of the position of the N/C
            "METSD",  # http://pubs.acs.org/doi/abs/10.1021/jz300207k and pubid 19089987
            "CYSSG",  # pubid 19089987, also when they from di-sulfide (Cys-Cys, fig 8 paper)
            "SEROG",  # isostar plots
            "THROG1",  # isostar plots
            "TYROH",  # isostar plots
        ]
    ),
    "xbond_donor": set(),
    "weak_hbond_acceptor": set(
        [
            "ALAO",  # all the carbonyl Oxygens in the main chain
            "ARGO",
            "ASNO",
            "ASPO",
            "CYSO",
            "GLNO",
            "GLUO",
            "GLYO",
            "HISO",
            "ILEO",
            "LEUO",
            "LYSO",
            "METO",
            "PHEO",
            "PROO",
            "SERO",
            "THRO",
            "TRPO",
            "TYRO",
            "VALO",
            "ALAOXT",  # all the carbonyl Oxygens terminals
            "ARGOXT",
            "ASNOXT",
            "ASPOXT",
            "CYSOXT",
            "GLNOXT",
            "GLUOXT",
            "GLYOXT",
            "HISOXT",
            "ILEOXT",
            "LEUOXT",
            "LYSOXT",
            "METOXT",
            "PHEOXT",
            "PROOXT",
            "SEROXT",
            "THROXT",
            "TRPOXT",
            "TYROXT",
            "VALOXT",
            "ASNOD1",
            "ASNND2",  # for the ambiguity of the position of the N and O
            "ASPOD1",
            "ASPOD2",
            "GLNOE1" "GLNNE2",  # for the ambiguity of the position of the N and O
            "GLUOE1",
            "GLUOE2",
            "HISND1",  # for the ambiguity of the position of the N/C
            "HISCE1",  # for the ambiguity of the position of the N/C
            "HISNE2",  # for the ambiguity of the position of the N/C
            "HISCD2",  # for the ambiguity of the position of the N/C
            "METSD",  # http://pubs.acs.org/doi/abs/10.1021/jz300207k and pubid 19089987
            "CYSSG",  # pubid 19089987, also when they from di-sulfide (Cys-Cys, fig 8 paper)
            "SEROG",  # isostar plots
            "THROG1",  # isostar plots
            "TYROH",  # isostar plots
        ]
    ),
    "weak_hbond_donor": set(
        [
            "ALACA",  # all the c-alphas
            "ARGCA",
            "ASNCA",
            "ASPCA",
            "CYSCA",
            "GLNCA",
            "GLUCA",
            "GLYCA",
            "HISCA",
            "ILECA",
            "LEUCA",
            "LYSCA",
            "METCA",
            "PHECA",
            "PROCA",
            "SERCA",
            "THRCA",
            "TRPCA",
            "TYRCA",
            "VALCA",
            "ALACB",  # cb and further down
            "ARGCB",
            "ARGCG",
            "ARGCD",
            "ASNCB",
            "ASPCB",
            "CYSCB",
            "GLNCB",
            "GLNCG",
            "GLUCB",
            "GLUCG",
            "GLNCB",
            "HISCB",
            "ILECB",
            "ILECG1",
            "ILECD1",
            "ILECG2",
            "LEUCB",
            "LEUCG",
            "LEUCD1",
            "LEUCD2",
            "LYSCB",
            "LYSCG",
            "LYSCD",
            "LYSCE",
            "METCB",
            "METCG",
            "METCE",
            "PHECB",
            "PHECG",
            "PHECD1",
            "PHECD2",
            "PHECE1",
            "PHECE2",
            "PHECZ",
            "PROCB",
            "PROCG",
            "PROCD",
            "SERCB",
            "THRCB",
            "THRCG2",
            "TRPCB",
            "TRPCD1" "TRPCE3",
            "TRPCZ3",
            "TRPCH2",
            "TRPCZ2",
            "TYRCB",
            "TYRCD1",
            "TYRCD2",
            "TYRCE1",
            "TYRCE2",
            "TRYCB",
            "VALCB",
            "VALCG1",
            "VALCG2",
        ]
    ),
    "pos_ionisable": set(
        [
            "ARGNE",
            "ARGCZ",
            "ARGNH1",
            "ARGNH2",
            "HISCG",
            "HISND1",
            "HISCE1",
            "HISNE2",
            "HISCD2",
            "LYSNZ",
        ]
    ),
    "neg_ionisable": set(["ASPOD1", "ASPOD2", "GLUOE1", "GLUOE2"]),
    "hydrophobe": set(
        [
            "ALACB",
            "ARGCB",
            "ARGCG",
            "ASNCB",
            "ASPCB",
            "CYSCB",  # sulfur in Cys has an Hydrogen, it is polarised
            "GLNCB",
            "GLNCG",
            "GLUCB",
            "GLUCG",
            "GLNCB",
            "HISCB",
            "ILECB",
            "ILECG1",
            "ILECD1",
            "ILECG2",
            "LEUCB",
            "LEUCG",
            "LEUCD1",
            "LEUCD2",
            "LYSCB",
            "LYSCG",
            "LYSCD",
            "METCB",
            "METCG",
            "METSD",
            "METCE",
            "PHECB",
            "PHECG",
            "PHECD1",
            "PHECD2",
            "PHECE1",
            "PHECE2",
            "PHECZ",
            "PROCB",
            "PROCG",
            "THRCG2",
            "TRPCB",
            "TRPCG",
            "TRPCD2",
            "TRPCE3",
            "TRPCZ3",
            "TRPCH2",
            "TRPCZ2",
            "TRYCB",
            "TYRCG",
            "TYRCD1",
            "TYRCD2",
            "TYRCE1",
            "TYRCE2",
            "VALCB",
            "VALCG1",
            "VALCG2",
        ]
    ),
    "carbonyl_oxygen": set(
        [
            "ALAO",  # all the carbonyl Oxygens in the main chain
            "ARGO",
            "ASNO",
            "ASPO",
            "CYSO",
            "GLNO",
            "GLUO",
            "GLYO",
            "HISO",
            "ILEO",
            "LEUO",
            "LYSO",
            "METO",
            "PHEO",
            "PROO",
            "SERO",
            "THRO",
            "TRPO",
            "TYRO",
            "VALO",
        ]
    ),
    "carbonyl_carbon": set(
        [
            "ALAC",
            "ARGC",
            "ASNC",
            "ASPC",
            "CYSC",
            "GLNC",
            "GLUC",
            "GLYC",
            "HISC",
            "ILEC",
            "LEUC",
            "LYSC",
            "METC",
            "PHEC",
            "PROC",
            "SERC",
            "THRC",
            "TRPC",
            "TYRC",
            "VALC",
        ]
    ),
    "aromatic": set(
        [
            "HISCG",
            "HISND1",
            "HISCE1",
            "HISNE2",
            "HISCD2",
            "PHECG",
            "PHECD1",
            "PHECD2",
            "PHECE1",
            "PHECE2",
            "PHECZ",
            "TRPCG",
            "TRPCD1",
            "TRPCD2",
            "TRPNE1",
            "TRPCE2",
            "TRPCE3",
            "TRPCZ2",
            "TRPCZ3",
            "TRPCH2",
            "TYRCG",
            "TYRCD1",
            "TYRCD2",
            "TYRCE1",
            "TYRCE2",
            "TYRCZ",
        ]
    ),
}

ID_TO_TYPES = {
    "PROO": {
        "carbonyl_oxygen",
        "hbond_acceptor",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "VALO": {
        "carbonyl_oxygen",
        "hbond_acceptor",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "TRPOXT": {"hbond_acceptor", "weak_hbond_acceptor", "xbond_acceptor"},
    "VALOXT": {"hbond_acceptor", "weak_hbond_acceptor", "xbond_acceptor"},
    "ALAOXT": {"hbond_acceptor", "weak_hbond_acceptor", "xbond_acceptor"},
    "GLNO": {
        "carbonyl_oxygen",
        "hbond_acceptor",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "HISO": {
        "carbonyl_oxygen",
        "hbond_acceptor",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "ASPOD2": {
        "hbond_acceptor",
        "neg_ionisable",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "ASPOD1": {
        "hbond_acceptor",
        "neg_ionisable",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "PHEOXT": {"hbond_acceptor", "weak_hbond_acceptor", "xbond_acceptor"},
    "ASPO": {
        "carbonyl_oxygen",
        "hbond_acceptor",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "HISOXT": {"hbond_acceptor", "weak_hbond_acceptor", "xbond_acceptor"},
    "ASNOXT": {"hbond_acceptor", "weak_hbond_acceptor", "xbond_acceptor"},
    "ALAO": {
        "carbonyl_oxygen",
        "hbond_acceptor",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "GLUOXT": {"hbond_acceptor", "weak_hbond_acceptor", "xbond_acceptor"},
    "GLUO": {
        "carbonyl_oxygen",
        "hbond_acceptor",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "TRPO": {
        "carbonyl_oxygen",
        "hbond_acceptor",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "ASNO": {
        "carbonyl_oxygen",
        "hbond_acceptor",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "TYRO": {
        "carbonyl_oxygen",
        "hbond_acceptor",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "ASNOD1": {
        "hbond_acceptor",
        "hbond_donor",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "ILEOXT": {"hbond_acceptor", "weak_hbond_acceptor", "xbond_acceptor"},
    "SEROXT": {"hbond_acceptor", "weak_hbond_acceptor", "xbond_acceptor"},
    "SERO": {
        "carbonyl_oxygen",
        "hbond_acceptor",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "GLNOE1GLNNE2": {"hbond_acceptor", "weak_hbond_acceptor", "xbond_acceptor"},
    "CYSSG": {"hbond_acceptor", "hbond_donor", "weak_hbond_acceptor", "xbond_acceptor"},
    "LYSO": {
        "carbonyl_oxygen",
        "hbond_acceptor",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "CYSOXT": {"hbond_acceptor", "weak_hbond_acceptor", "xbond_acceptor"},
    "ARGOXT": {"hbond_acceptor", "weak_hbond_acceptor", "xbond_acceptor"},
    "LEUO": {
        "carbonyl_oxygen",
        "hbond_acceptor",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "THROXT": {"hbond_acceptor", "weak_hbond_acceptor", "xbond_acceptor"},
    "HISCD2": {
        "aromatic",
        "hbond_acceptor",
        "hbond_donor",
        "pos_ionisable",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "LYSOXT": {"hbond_acceptor", "weak_hbond_acceptor", "xbond_acceptor"},
    "TYROXT": {"hbond_acceptor", "weak_hbond_acceptor", "xbond_acceptor"},
    "HISCE1": {
        "aromatic",
        "hbond_acceptor",
        "hbond_donor",
        "pos_ionisable",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "HISND1": {
        "aromatic",
        "hbond_acceptor",
        "hbond_donor",
        "pos_ionisable",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "ASPOXT": {"hbond_acceptor", "weak_hbond_acceptor", "xbond_acceptor"},
    "METO": {
        "carbonyl_oxygen",
        "hbond_acceptor",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "CYSO": {
        "carbonyl_oxygen",
        "hbond_acceptor",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "TYROH": {"hbond_acceptor", "hbond_donor", "weak_hbond_acceptor", "xbond_acceptor"},
    "LEUOXT": {"hbond_acceptor", "weak_hbond_acceptor", "xbond_acceptor"},
    "GLUOE1": {
        "hbond_acceptor",
        "neg_ionisable",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "ILEO": {
        "carbonyl_oxygen",
        "hbond_acceptor",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "ARGO": {
        "carbonyl_oxygen",
        "hbond_acceptor",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "GLNOXT": {"hbond_acceptor", "weak_hbond_acceptor", "xbond_acceptor"},
    "HISNE2": {
        "aromatic",
        "hbond_acceptor",
        "hbond_donor",
        "pos_ionisable",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "GLYOXT": {"hbond_acceptor", "weak_hbond_acceptor", "xbond_acceptor"},
    "GLUOE2": {
        "hbond_acceptor",
        "neg_ionisable",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "THRO": {
        "carbonyl_oxygen",
        "hbond_acceptor",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "SEROG": {"hbond_acceptor", "hbond_donor", "weak_hbond_acceptor", "xbond_acceptor"},
    "PROOXT": {"hbond_acceptor", "weak_hbond_acceptor", "xbond_acceptor"},
    "THROG1": {
        "hbond_acceptor",
        "hbond_donor",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "PHEO": {
        "carbonyl_oxygen",
        "hbond_acceptor",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "METOXT": {"hbond_acceptor", "weak_hbond_acceptor", "xbond_acceptor"},
    "METSD": {"hbond_acceptor", "hydrophobe", "weak_hbond_acceptor", "xbond_acceptor"},
    "GLYO": {
        "carbonyl_oxygen",
        "hbond_acceptor",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "ASNND2": {
        "hbond_acceptor",
        "hbond_donor",
        "weak_hbond_acceptor",
        "xbond_acceptor",
    },
    "ARGN": {"hbond_donor"},
    "METN": {"hbond_donor"},
    "HISN": {"hbond_donor"},
    "GLNOE1": {"hbond_donor"},
    "TRPNE1": {"aromatic", "hbond_donor"},
    "ASNN": {"hbond_donor"},
    "ARGNH1": {"hbond_donor", "pos_ionisable"},
    "ILEN": {"hbond_donor"},
    "SERN": {"hbond_donor"},
    "ALAN": {"hbond_donor"},
    "THRN": {"hbond_donor"},
    "CYSN": {"hbond_donor"},
    "GLNN": {"hbond_donor"},
    "GLNNE2": {"hbond_donor"},
    "GLYN": {"hbond_donor"},
    "TRPN": {"hbond_donor"},
    "ARGNH2": {"hbond_donor", "pos_ionisable"},
    "TYRN": {"hbond_donor"},
    "LYSNZ": {"hbond_donor", "pos_ionisable"},
    "ASPN": {"hbond_donor"},
    "PHEN": {"hbond_donor"},
    "VALN": {"hbond_donor"},
    "ARGNE": {"hbond_donor", "pos_ionisable"},
    "LEUN": {"hbond_donor"},
    "GLUN": {"hbond_donor"},
    "LYSN": {"hbond_donor"},
    "PROCA": {"weak hbond_donor"},
    "TRPCZ3": {"aromatic", "hydrophobe", "weak hbond_donor"},
    "GLYCA": {"weak hbond_donor"},
    "VALCG1": {"hydrophobe", "weak hbond_donor"},
    "ILECD1": {"hydrophobe", "weak hbond_donor"},
    "GLNCA": {"weak hbond_donor"},
    "LYSCA": {"weak hbond_donor"},
    "GLNCB": {"hydrophobe", "weak hbond_donor"},
    "VALCA": {"weak hbond_donor"},
    "ILECA": {"weak hbond_donor"},
    "GLUCG": {"hydrophobe", "weak hbond_donor"},
    "TYRCD1": {"aromatic", "hydrophobe", "weak hbond_donor"},
    "ALACA": {"weak hbond_donor"},
    "METCB": {"hydrophobe", "weak hbond_donor"},
    "ILECG2": {"hydrophobe", "weak hbond_donor"},
    "LYSCD": {"hydrophobe", "weak hbond_donor"},
    "LEUCB": {"hydrophobe", "weak hbond_donor"},
    "THRCA": {"weak hbond_donor"},
    "ARGCG": {"hydrophobe", "weak hbond_donor"},
    "LYSCB": {"hydrophobe", "weak hbond_donor"},
    "LYSCG": {"hydrophobe", "weak hbond_donor"},
    "TRYCB": {"hydrophobe", "weak hbond_donor"},
    "CYSCA": {"weak hbond_donor"},
    "PHECZ": {"aromatic", "hydrophobe", "weak hbond_donor"},
    "ILECB": {"hydrophobe", "weak hbond_donor"},
    "ASNCA": {"weak hbond_donor"},
    "ARGCD": {"weak hbond_donor"},
    "LEUCA": {"weak hbond_donor"},
    "PHECG": {"aromatic", "hydrophobe", "weak hbond_donor"},
    "THRCB": {"weak hbond_donor"},
    "ARGCB": {"hydrophobe", "weak hbond_donor"},
    "ASPCA": {"weak hbond_donor"},
    "PHECA": {"weak hbond_donor"},
    "CYSCB": {"hydrophobe", "weak hbond_donor"},
    "THRCG2": {"hydrophobe", "weak hbond_donor"},
    "HISCB": {"hydrophobe", "weak hbond_donor"},
    "TRPCD1TRPCE3": {"weak hbond_donor"},
    "PROCB": {"hydrophobe", "weak hbond_donor"},
    "LEUCD1": {"hydrophobe", "weak hbond_donor"},
    "SERCA": {"weak hbond_donor"},
    "TRPCZ2": {"aromatic", "hydrophobe", "weak hbond_donor"},
    "LEUCD2": {"hydrophobe", "weak hbond_donor"},
    "ARGCA": {"weak hbond_donor"},
    "PHECE1": {"aromatic", "hydrophobe", "weak hbond_donor"},
    "METCE": {"hydrophobe", "weak hbond_donor"},
    "TYRCB": {"weak hbond_donor"},
    "VALCB": {"hydrophobe", "weak hbond_donor"},
    "ALACB": {"hydrophobe", "weak hbond_donor"},
    "PROCD": {"weak hbond_donor"},
    "ILECG1": {"hydrophobe", "weak hbond_donor"},
    "PROCG": {"hydrophobe", "weak hbond_donor"},
    "PHECD2": {"aromatic", "hydrophobe", "weak hbond_donor"},
    "TRPCB": {"hydrophobe", "weak hbond_donor"},
    "GLUCA": {"weak hbond_donor"},
    "HISCA": {"weak hbond_donor"},
    "SERCB": {"weak hbond_donor"},
    "TYRCE2": {"aromatic", "hydrophobe", "weak hbond_donor"},
    "TRPCA": {"weak hbond_donor"},
    "ASNCB": {"hydrophobe", "weak hbond_donor"},
    "ASPCB": {"hydrophobe", "weak hbond_donor"},
    "TYRCA": {"weak hbond_donor"},
    "PHECD1": {"aromatic", "hydrophobe", "weak hbond_donor"},
    "TYRCE1": {"aromatic", "hydrophobe", "weak hbond_donor"},
    "METCG": {"hydrophobe", "weak hbond_donor"},
    "VALCG2": {"hydrophobe", "weak hbond_donor"},
    "GLNCG": {"hydrophobe", "weak hbond_donor"},
    "GLUCB": {"hydrophobe", "weak hbond_donor"},
    "LEUCG": {"hydrophobe", "weak hbond_donor"},
    "PHECB": {"hydrophobe", "weak hbond_donor"},
    "TRPCH2": {"aromatic", "hydrophobe", "weak hbond_donor"},
    "TYRCD2": {"aromatic", "hydrophobe", "weak hbond_donor"},
    "LYSCE": {"weak hbond_donor"},
    "METCA": {"weak hbond_donor"},
    "PHECE2": {"aromatic", "hydrophobe", "weak hbond_donor"},
    "HISCG": {"aromatic", "pos_ionisable"},
    "ARGCZ": {"pos_ionisable"},
    "TRPCE3": {"aromatic", "hydrophobe"},
    "TRPCG": {"aromatic", "hydrophobe"},
    "TYRCG": {"aromatic", "hydrophobe"},
    "TRPCD2": {"aromatic", "hydrophobe"},
    "CYSC": {"carbonyl_carbon"},
    "ILEC": {"carbonyl_carbon"},
    "METC": {"carbonyl_carbon"},
    "LEUC": {"carbonyl_carbon"},
    "LYSC": {"carbonyl_carbon"},
    "PROC": {"carbonyl_carbon"},
    "THRC": {"carbonyl_carbon"},
    "GLNC": {"carbonyl_carbon"},
    "ASNC": {"carbonyl_carbon"},
    "ARGC": {"carbonyl_carbon"},
    "ALAC": {"carbonyl_carbon"},
    "PHEC": {"carbonyl_carbon"},
    "HISC": {"carbonyl_carbon"},
    "GLUC": {"carbonyl_carbon"},
    "TYRC": {"carbonyl_carbon"},
    "SERC": {"carbonyl_carbon"},
    "VALC": {"carbonyl_carbon"},
    "ASPC": {"carbonyl_carbon"},
    "GLYC": {"carbonyl_carbon"},
    "TRPC": {"carbonyl_carbon"},
    "TYRCZ": {"aromatic"},
    "TRPCD1": {"aromatic"},
    "TRPCE2": {"aromatic"},
}
