# NAMES
HALOGENS = set(["F", "CL", "BR", "I", "AT"])

MAINCHAIN_ATOMS = set(["N", "C", "CA", "O", "OXT"])

METALS = set(
    [
        "Li",
        "Be",
        "Na",
        "Mg",
        "Aa",
        "K",
        "Ca",
        "Sc",
        "Ti",
        "V",
        "Cr",
        "Mn",
        "Fe",
        "Co",
        "Ni",
        "Cu",
        "Zn",
        "Ga",
        "Rb",
        "Sr",
        "Y",
        "Zr",
        "Nb",
        "Mo",
        "Tc",
        "Ru",
        "Rh",
        "Pd",
        "Ag",
        "Cd",
        "In",
        "Sn",
        "Cs",
        "Ba",
        "La",
        "Ce",
        "Pr",
        "Nd",
        "Pm",
        "Sm",
        "Eu",
        "Gd",
        "Tb",
        "Dy",
        "Ho",
        "Er",
        "Tm",
        "Yb",
        "Lu",
        "Hf",
        "Ta",
        "W",
        "Re",
        "Os",
        "Ir",
        "Pt",
        "Au",
        "Hg",
        "Tl",
        "Pb",
        "Bi",
        "Po",
        "Fr",
        "Ra",
        "Ac",
        "Th",
        "Pa",
        "U",
        "Np",
        "Pu",
        "Am",
        "Cm",
        "Bk",
        "Cf",
    ]
)

# TYPES
PROT_ATOM_TYPES = {
    "hbond acceptor": set(
        [
            "ALAO",  # all the carbonyl Oxygens in the main chain
            "ARGO",
            "ASNO",
            "ASPO",
            "CYSO",
            "GLNO",
            "GLUO",
            "GLYO",
            "HISO",
            "ILEO",
            "LEUO",
            "LYSO",
            "METO",
            "PHEO",
            "PROO",
            "SERO",
            "THRO",
            "TRPO",
            "TYRO",
            "VALO",
            "ALAOXT",  # all the carbonyl Oxygens terminals
            "ARGOXT",
            "ASNOXT",
            "ASPOXT",
            "CYSOXT",
            "GLNOXT",
            "GLUOXT",
            "GLYOXT",
            "HISOXT",
            "ILEOXT",
            "LEUOXT",
            "LYSOXT",
            "METOXT",
            "PHEOXT",
            "PROOXT",
            "SEROXT",
            "THROXT",
            "TRPOXT",
            "TYROXT",
            "VALOXT",
            "ASNOD1",
            "ASNND2",  # for the ambiguity of the position of the N and O
            "ASPOD1",
            "ASPOD2",
            "GLNOE1" "GLNNE2",  # for the ambiguity of the position of the N and O
            "GLUOE1",
            "GLUOE2",
            "HISND1",  # for the ambiguity of the position of the N/C
            "HISCE1",  # for the ambiguity of the position of the N/C
            "HISNE2",  # for the ambiguity of the position of the N/C
            "HISCD2",  # for the ambiguity of the position of the N/C
            "METSD",  # http://pubs.acs.org/doi/abs/10.1021/jz300207k and pubid 19089987
            "CYSSG",  # pubid 19089987, also when they from di-sulfide (Cys-Cys, fig 8 paper)
            "SEROG",  # isostar plots
            "THROG1",  # isostar plots
            "TYROH",  # isostar plots
        ]
    ),
    "hbond donor": set(
        [
            "ALAN",  # all the amide nitrogens in the main chain except proline
            "ARGN",
            "ASNN",
            "ASPN",
            "CYSN",
            "GLNN",
            "GLUN",
            "GLYN",
            "HISN",
            "ILEN",
            "LEUN",
            "LYSN",
            "METN",
            "PHEN",
            "SERN",
            "THRN",
            "TRPN",
            "TYRN",
            "VALN",
            "ARGNE",
            "ARGNH1",
            "ARGNH2",
            "ASNND2",
            "ASNOD1",  # for the ambiguity of the position of the N and O
            "CYSSG",  # http://www.ncbi.nlm.nih.gov/pubmed/19089987
            "GLNNE2",
            "GLNOE1",  # for the ambiguity of the position of N/O
            "HISND1",  # for the ambiguity of the position of the N/C
            "HISCE1",  # for the ambiguity of the position of the N/C
            "HISNE2",  # for the ambiguity of the position of the N/C
            "HISCD2",  # for the ambiguity of the position of the N/C
            "LYSNZ",
            "SEROG",
            "THROG1",
            "TRPNE1",
            "TYROH",
        ]
    ),
    "xbond acceptor": set(
        [
            "ALAO",  # all the carbonyl Oxygens in the main chain
            "ARGO",
            "ASNO",
            "ASPO",
            "CYSO",
            "GLNO",
            "GLUO",
            "GLYO",
            "HISO",
            "ILEO",
            "LEUO",
            "LYSO",
            "METO",
            "PHEO",
            "PROO",
            "SERO",
            "THRO",
            "TRPO",
            "TYRO",
            "VALO",
            "ALAOXT",  # all the carbonyl Oxygens terminals
            "ARGOXT",
            "ASNOXT",
            "ASPOXT",
            "CYSOXT",
            "GLNOXT",
            "GLUOXT",
            "GLYOXT",
            "HISOXT",
            "ILEOXT",
            "LEUOXT",
            "LYSOXT",
            "METOXT",
            "PHEOXT",
            "PROOXT",
            "SEROXT",
            "THROXT",
            "TRPOXT",
            "TYROXT",
            "VALOXT",
            "ASNOD1",
            "ASNND2",  # for the ambiguity of the position of the N and O
            "ASPOD1",
            "ASPOD2",
            "GLNOE1" "GLNNE2",  # for the ambiguity of the position of the N and O
            "GLUOE1",
            "GLUOE2",
            "HISND1",  # for the ambiguity of the position of the N/C
            "HISCE1",  # for the ambiguity of the position of the N/C
            "HISNE2",  # for the ambiguity of the position of the N/C
            "HISCD2",  # for the ambiguity of the position of the N/C
            "METSD",  # http://pubs.acs.org/doi/abs/10.1021/jz300207k and pubid 19089987
            "CYSSG",  # pubid 19089987, also when they from di-sulfide (Cys-Cys, fig 8 paper)
            "SEROG",  # isostar plots
            "THROG1",  # isostar plots
            "TYROH",  # isostar plots
        ]
    ),
    "weak hbond acceptor": set(
        [
            "ALAO",  # all the carbonyl Oxygens in the main chain
            "ARGO",
            "ASNO",
            "ASPO",
            "CYSO",
            "GLNO",
            "GLUO",
            "GLYO",
            "HISO",
            "ILEO",
            "LEUO",
            "LYSO",
            "METO",
            "PHEO",
            "PROO",
            "SERO",
            "THRO",
            "TRPO",
            "TYRO",
            "VALO",
            "ALAOXT",  # all the carbonyl Oxygens terminals
            "ARGOXT",
            "ASNOXT",
            "ASPOXT",
            "CYSOXT",
            "GLNOXT",
            "GLUOXT",
            "GLYOXT",
            "HISOXT",
            "ILEOXT",
            "LEUOXT",
            "LYSOXT",
            "METOXT",
            "PHEOXT",
            "PROOXT",
            "SEROXT",
            "THROXT",
            "TRPOXT",
            "TYROXT",
            "VALOXT",
            "ASNOD1",
            "ASNND2",  # for the ambiguity of the position of the N and O
            "ASPOD1",
            "ASPOD2",
            "GLNOE1" "GLNNE2",  # for the ambiguity of the position of the N and O
            "GLUOE1",
            "GLUOE2",
            "HISND1",  # for the ambiguity of the position of the N/C
            "HISCE1",  # for the ambiguity of the position of the N/C
            "HISNE2",  # for the ambiguity of the position of the N/C
            "HISCD2",  # for the ambiguity of the position of the N/C
            "METSD",  # http://pubs.acs.org/doi/abs/10.1021/jz300207k and pubid 19089987
            "CYSSG",  # pubid 19089987, also when they from di-sulfide (Cys-Cys, fig 8 paper)
            "SEROG",  # isostar plots
            "THROG1",  # isostar plots
            "TYROH",  # isostar plots
        ]
    ),
    "weak hbond donor": set(
        [
            "ALACA",  # all the c-alphas
            "ARGCA",
            "ASNCA",
            "ASPCA",
            "CYSCA",
            "GLNCA",
            "GLUCA",
            "GLYCA",
            "HISCA",
            "ILECA",
            "LEUCA",
            "LYSCA",
            "METCA",
            "PHECA",
            "PROCA",
            "SERCA",
            "THRCA",
            "TRPCA",
            "TYRCA",
            "VALCA",
            "ALACB",  # cb and further down
            "ARGCB",
            "ARGCG",
            "ARGCD",
            "ASNCB",
            "ASPCB",
            "CYSCB",
            "GLNCB",
            "GLNCG",
            "GLUCB",
            "GLUCG",
            "GLNCB",
            "HISCB",
            "ILECB",
            "ILECG1",
            "ILECD1",
            "ILECG2",
            "LEUCB",
            "LEUCG",
            "LEUCD1",
            "LEUCD2",
            "LYSCB",
            "LYSCG",
            "LYSCD",
            "LYSCE",
            "METCB",
            "METCG",
            "METCE",
            "PHECB",
            "PHECG",
            "PHECD1",
            "PHECD2",
            "PHECE1",
            "PHECE2",
            "PHECZ",
            "PROCB",
            "PROCG",
            "PROCD",
            "SERCB",
            "THRCB",
            "THRCG2",
            "TRPCB",
            "TRPCD1" "TRPCE3",
            "TRPCZ3",
            "TRPCH2",
            "TRPCZ2",
            "TYRCB",
            "TYRCD1",
            "TYRCD2",
            "TYRCE1",
            "TYRCE2",
            "TRYCB",
            "VALCB",
            "VALCG1",
            "VALCG2",
        ]
    ),
    "pos ionisable": set(
        [
            "ARGNE",
            "ARGCZ",
            "ARGNH1",
            "ARGNH2",
            "HISCG",
            "HISND1",
            "HISCE1",
            "HISNE2",
            "HISCD2",
            "LYSNZ",
        ]
    ),
    "neg ionisable": set(["ASPOD1", "ASPOD2", "GLUOE1", "GLUOE2"]),
    "hydrophobe": set(
        [
            "ALACB",
            "ARGCB",
            "ARGCG",
            "ASNCB",
            "ASPCB",
            "CYSCB",  # sulfur in Cys has an Hydrogen, it is polarised
            "GLNCB",
            "GLNCG",
            "GLUCB",
            "GLUCG",
            "GLNCB",
            "HISCB",
            "ILECB",
            "ILECG1",
            "ILECD1",
            "ILECG2",
            "LEUCB",
            "LEUCG",
            "LEUCD1",
            "LEUCD2",
            "LYSCB",
            "LYSCG",
            "LYSCD",
            "METCB",
            "METCG",
            "METSD",
            "METCE",
            "PHECB",
            "PHECG",
            "PHECD1",
            "PHECD2",
            "PHECE1",
            "PHECE2",
            "PHECZ",
            "PROCB",
            "PROCG",
            "THRCG2",
            "TRPCB",
            "TRPCG",
            "TRPCD2",
            "TRPCE3",
            "TRPCZ3",
            "TRPCH2",
            "TRPCZ2",
            "TRYCB",
            "TYRCG",
            "TYRCD1",
            "TYRCD2",
            "TYRCE1",
            "TYRCE2",
            "VALCB",
            "VALCG1",
            "VALCG2",
        ]
    ),
    "carbonyl oxygen": set(
        [
            "ALAO",  # all the carbonyl Oxygens in the main chain
            "ARGO",
            "ASNO",
            "ASPO",
            "CYSO",
            "GLNO",
            "GLUO",
            "GLYO",
            "HISO",
            "ILEO",
            "LEUO",
            "LYSO",
            "METO",
            "PHEO",
            "PROO",
            "SERO",
            "THRO",
            "TRPO",
            "TYRO",
            "VALO",
        ]
    ),
    "carbonyl carbon": set(
        [
            "ALAC",
            "ARGC",
            "ASNC",
            "ASPC",
            "CYSC",
            "GLNC",
            "GLUC",
            "GLYC",
            "HISC",
            "ILEC",
            "LEUC",
            "LYSC",
            "METC",
            "PHEC",
            "PROC",
            "SERC",
            "THRC",
            "TRPC",
            "TYRC",
            "VALC",
        ]
    ),
    "aromatic": set(
        [
            "HISCG",
            "HISND1",
            "HISCE1",
            "HISNE2",
            "HISCD2",
            "PHECG",
            "PHECD1",
            "PHECD2",
            "PHECE1",
            "PHECE2",
            "PHECZ",
            "TRPCG",
            "TRPCD1",
            "TRPCD2",
            "TRPNE1",
            "TRPCE2",
            "TRPCE3",
            "TRPCZ2",
            "TRPCZ3",
            "TRPCH2",
            "TYRCG",
            "TYRCD1",
            "TYRCD2",
            "TYRCE1",
            "TYRCE2",
            "TYRCZ",
        ]
    ),
}

ID_TO_TYPES = {
    "PROO": {
        "carbonyl oxygen",
        "hbond acceptor",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "VALO": {
        "carbonyl oxygen",
        "hbond acceptor",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "TRPOXT": {"hbond acceptor", "weak hbond acceptor", "xbond acceptor"},
    "VALOXT": {"hbond acceptor", "weak hbond acceptor", "xbond acceptor"},
    "ALAOXT": {"hbond acceptor", "weak hbond acceptor", "xbond acceptor"},
    "GLNO": {
        "carbonyl oxygen",
        "hbond acceptor",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "HISO": {
        "carbonyl oxygen",
        "hbond acceptor",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "ASPOD2": {
        "hbond acceptor",
        "neg ionisable",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "ASPOD1": {
        "hbond acceptor",
        "neg ionisable",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "PHEOXT": {"hbond acceptor", "weak hbond acceptor", "xbond acceptor"},
    "ASPO": {
        "carbonyl oxygen",
        "hbond acceptor",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "HISOXT": {"hbond acceptor", "weak hbond acceptor", "xbond acceptor"},
    "ASNOXT": {"hbond acceptor", "weak hbond acceptor", "xbond acceptor"},
    "ALAO": {
        "carbonyl oxygen",
        "hbond acceptor",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "GLUOXT": {"hbond acceptor", "weak hbond acceptor", "xbond acceptor"},
    "GLUO": {
        "carbonyl oxygen",
        "hbond acceptor",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "TRPO": {
        "carbonyl oxygen",
        "hbond acceptor",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "ASNO": {
        "carbonyl oxygen",
        "hbond acceptor",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "TYRO": {
        "carbonyl oxygen",
        "hbond acceptor",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "ASNOD1": {
        "hbond acceptor",
        "hbond donor",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "ILEOXT": {"hbond acceptor", "weak hbond acceptor", "xbond acceptor"},
    "SEROXT": {"hbond acceptor", "weak hbond acceptor", "xbond acceptor"},
    "SERO": {
        "carbonyl oxygen",
        "hbond acceptor",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "GLNOE1GLNNE2": {"hbond acceptor", "weak hbond acceptor", "xbond acceptor"},
    "CYSSG": {"hbond acceptor", "hbond donor", "weak hbond acceptor", "xbond acceptor"},
    "LYSO": {
        "carbonyl oxygen",
        "hbond acceptor",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "CYSOXT": {"hbond acceptor", "weak hbond acceptor", "xbond acceptor"},
    "ARGOXT": {"hbond acceptor", "weak hbond acceptor", "xbond acceptor"},
    "LEUO": {
        "carbonyl oxygen",
        "hbond acceptor",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "THROXT": {"hbond acceptor", "weak hbond acceptor", "xbond acceptor"},
    "HISCD2": {
        "aromatic",
        "hbond acceptor",
        "hbond donor",
        "pos ionisable",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "LYSOXT": {"hbond acceptor", "weak hbond acceptor", "xbond acceptor"},
    "TYROXT": {"hbond acceptor", "weak hbond acceptor", "xbond acceptor"},
    "HISCE1": {
        "aromatic",
        "hbond acceptor",
        "hbond donor",
        "pos ionisable",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "HISND1": {
        "aromatic",
        "hbond acceptor",
        "hbond donor",
        "pos ionisable",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "ASPOXT": {"hbond acceptor", "weak hbond acceptor", "xbond acceptor"},
    "METO": {
        "carbonyl oxygen",
        "hbond acceptor",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "CYSO": {
        "carbonyl oxygen",
        "hbond acceptor",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "TYROH": {"hbond acceptor", "hbond donor", "weak hbond acceptor", "xbond acceptor"},
    "LEUOXT": {"hbond acceptor", "weak hbond acceptor", "xbond acceptor"},
    "GLUOE1": {
        "hbond acceptor",
        "neg ionisable",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "ILEO": {
        "carbonyl oxygen",
        "hbond acceptor",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "ARGO": {
        "carbonyl oxygen",
        "hbond acceptor",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "GLNOXT": {"hbond acceptor", "weak hbond acceptor", "xbond acceptor"},
    "HISNE2": {
        "aromatic",
        "hbond acceptor",
        "hbond donor",
        "pos ionisable",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "GLYOXT": {"hbond acceptor", "weak hbond acceptor", "xbond acceptor"},
    "GLUOE2": {
        "hbond acceptor",
        "neg ionisable",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "THRO": {
        "carbonyl oxygen",
        "hbond acceptor",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "SEROG": {"hbond acceptor", "hbond donor", "weak hbond acceptor", "xbond acceptor"},
    "PROOXT": {"hbond acceptor", "weak hbond acceptor", "xbond acceptor"},
    "THROG1": {
        "hbond acceptor",
        "hbond donor",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "PHEO": {
        "carbonyl oxygen",
        "hbond acceptor",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "METOXT": {"hbond acceptor", "weak hbond acceptor", "xbond acceptor"},
    "METSD": {"hbond acceptor", "hydrophobe", "weak hbond acceptor", "xbond acceptor"},
    "GLYO": {
        "carbonyl oxygen",
        "hbond acceptor",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "ASNND2": {
        "hbond acceptor",
        "hbond donor",
        "weak hbond acceptor",
        "xbond acceptor",
    },
    "ARGN": {"hbond donor"},
    "METN": {"hbond donor"},
    "HISN": {"hbond donor"},
    "GLNOE1": {"hbond donor"},
    "TRPNE1": {"aromatic", "hbond donor"},
    "ASNN": {"hbond donor"},
    "ARGNH1": {"hbond donor", "pos ionisable"},
    "ILEN": {"hbond donor"},
    "SERN": {"hbond donor"},
    "ALAN": {"hbond donor"},
    "THRN": {"hbond donor"},
    "CYSN": {"hbond donor"},
    "GLNN": {"hbond donor"},
    "GLNNE2": {"hbond donor"},
    "GLYN": {"hbond donor"},
    "TRPN": {"hbond donor"},
    "ARGNH2": {"hbond donor", "pos ionisable"},
    "TYRN": {"hbond donor"},
    "LYSNZ": {"hbond donor", "pos ionisable"},
    "ASPN": {"hbond donor"},
    "PHEN": {"hbond donor"},
    "VALN": {"hbond donor"},
    "ARGNE": {"hbond donor", "pos ionisable"},
    "LEUN": {"hbond donor"},
    "GLUN": {"hbond donor"},
    "LYSN": {"hbond donor"},
    "PROCA": {"weak hbond donor"},
    "TRPCZ3": {"aromatic", "hydrophobe", "weak hbond donor"},
    "GLYCA": {"weak hbond donor"},
    "VALCG1": {"hydrophobe", "weak hbond donor"},
    "ILECD1": {"hydrophobe", "weak hbond donor"},
    "GLNCA": {"weak hbond donor"},
    "LYSCA": {"weak hbond donor"},
    "GLNCB": {"hydrophobe", "weak hbond donor"},
    "VALCA": {"weak hbond donor"},
    "ILECA": {"weak hbond donor"},
    "GLUCG": {"hydrophobe", "weak hbond donor"},
    "TYRCD1": {"aromatic", "hydrophobe", "weak hbond donor"},
    "ALACA": {"weak hbond donor"},
    "METCB": {"hydrophobe", "weak hbond donor"},
    "ILECG2": {"hydrophobe", "weak hbond donor"},
    "LYSCD": {"hydrophobe", "weak hbond donor"},
    "LEUCB": {"hydrophobe", "weak hbond donor"},
    "THRCA": {"weak hbond donor"},
    "ARGCG": {"hydrophobe", "weak hbond donor"},
    "LYSCB": {"hydrophobe", "weak hbond donor"},
    "LYSCG": {"hydrophobe", "weak hbond donor"},
    "TRYCB": {"hydrophobe", "weak hbond donor"},
    "CYSCA": {"weak hbond donor"},
    "PHECZ": {"aromatic", "hydrophobe", "weak hbond donor"},
    "ILECB": {"hydrophobe", "weak hbond donor"},
    "ASNCA": {"weak hbond donor"},
    "ARGCD": {"weak hbond donor"},
    "LEUCA": {"weak hbond donor"},
    "PHECG": {"aromatic", "hydrophobe", "weak hbond donor"},
    "THRCB": {"weak hbond donor"},
    "ARGCB": {"hydrophobe", "weak hbond donor"},
    "ASPCA": {"weak hbond donor"},
    "PHECA": {"weak hbond donor"},
    "CYSCB": {"hydrophobe", "weak hbond donor"},
    "THRCG2": {"hydrophobe", "weak hbond donor"},
    "HISCB": {"hydrophobe", "weak hbond donor"},
    "TRPCD1TRPCE3": {"weak hbond donor"},
    "PROCB": {"hydrophobe", "weak hbond donor"},
    "LEUCD1": {"hydrophobe", "weak hbond donor"},
    "SERCA": {"weak hbond donor"},
    "TRPCZ2": {"aromatic", "hydrophobe", "weak hbond donor"},
    "LEUCD2": {"hydrophobe", "weak hbond donor"},
    "ARGCA": {"weak hbond donor"},
    "PHECE1": {"aromatic", "hydrophobe", "weak hbond donor"},
    "METCE": {"hydrophobe", "weak hbond donor"},
    "TYRCB": {"weak hbond donor"},
    "VALCB": {"hydrophobe", "weak hbond donor"},
    "ALACB": {"hydrophobe", "weak hbond donor"},
    "PROCD": {"weak hbond donor"},
    "ILECG1": {"hydrophobe", "weak hbond donor"},
    "PROCG": {"hydrophobe", "weak hbond donor"},
    "PHECD2": {"aromatic", "hydrophobe", "weak hbond donor"},
    "TRPCB": {"hydrophobe", "weak hbond donor"},
    "GLUCA": {"weak hbond donor"},
    "HISCA": {"weak hbond donor"},
    "SERCB": {"weak hbond donor"},
    "TYRCE2": {"aromatic", "hydrophobe", "weak hbond donor"},
    "TRPCA": {"weak hbond donor"},
    "ASNCB": {"hydrophobe", "weak hbond donor"},
    "ASPCB": {"hydrophobe", "weak hbond donor"},
    "TYRCA": {"weak hbond donor"},
    "PHECD1": {"aromatic", "hydrophobe", "weak hbond donor"},
    "TYRCE1": {"aromatic", "hydrophobe", "weak hbond donor"},
    "METCG": {"hydrophobe", "weak hbond donor"},
    "VALCG2": {"hydrophobe", "weak hbond donor"},
    "GLNCG": {"hydrophobe", "weak hbond donor"},
    "GLUCB": {"hydrophobe", "weak hbond donor"},
    "LEUCG": {"hydrophobe", "weak hbond donor"},
    "PHECB": {"hydrophobe", "weak hbond donor"},
    "TRPCH2": {"aromatic", "hydrophobe", "weak hbond donor"},
    "TYRCD2": {"aromatic", "hydrophobe", "weak hbond donor"},
    "LYSCE": {"weak hbond donor"},
    "METCA": {"weak hbond donor"},
    "PHECE2": {"aromatic", "hydrophobe", "weak hbond donor"},
    "HISCG": {"aromatic", "pos ionisable"},
    "ARGCZ": {"pos ionisable"},
    "TRPCE3": {"aromatic", "hydrophobe"},
    "TRPCG": {"aromatic", "hydrophobe"},
    "TYRCG": {"aromatic", "hydrophobe"},
    "TRPCD2": {"aromatic", "hydrophobe"},
    "CYSC": {"carbonyl carbon"},
    "ILEC": {"carbonyl carbon"},
    "METC": {"carbonyl carbon"},
    "LEUC": {"carbonyl carbon"},
    "LYSC": {"carbonyl carbon"},
    "PROC": {"carbonyl carbon"},
    "THRC": {"carbonyl carbon"},
    "GLNC": {"carbonyl carbon"},
    "ASNC": {"carbonyl carbon"},
    "ARGC": {"carbonyl carbon"},
    "ALAC": {"carbonyl carbon"},
    "PHEC": {"carbonyl carbon"},
    "HISC": {"carbonyl carbon"},
    "GLUC": {"carbonyl carbon"},
    "TYRC": {"carbonyl carbon"},
    "SERC": {"carbonyl carbon"},
    "VALC": {"carbonyl carbon"},
    "ASPC": {"carbonyl carbon"},
    "GLYC": {"carbonyl carbon"},
    "TRPC": {"carbonyl carbon"},
    "TYRCZ": {"aromatic"},
    "TRPCD1": {"aromatic"},
    "TRPCE2": {"aromatic"},
}
