from dataclasses import dataclass
from typing import Any, ClassVar, Self, overload, TypeAlias

import numpy as np
from numpy.typing import NDArray

# NOTE: it would be nice to simplify the typing by encapsulating the `list`
# and `NDArray` types in a custom type alias or protocol, but type checkers
# do not expand these, so the user is left wondering what StrIter is.
# class StrIter(Protocol):
#     def __iter__(self) -> Iterator[str]: ...
# StrIter: TypeAlias = list[str] | NDArray[np.str_]

Labels: TypeAlias = list[str] | NDArray[np.str_]
Indices: TypeAlias = list[int] | NDArray[np.int32]

# Intermediate Representation
@dataclass
class IR:
    atom_indices: list[int] | NDArray[np.int32]
    atomic_numbers: list[int] | NDArray[np.int32]
    atom_names: list[str] | NDArray[np.str_]
    resids: list[int] | NDArray[np.int32]
    resnames: list[str] | NDArray[np.str_]
    chainlabels: list[str] | NDArray[np.str_]
    positions: NDArray[np.float32]

class LahutaCPP:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, filename: str) -> None: ...
    @overload
    def __init__(self, ir: IR) -> None: ...
    def get_positions(self) -> list[list[float]]: ...
    # def filter(self) -> LahutaCPP: ...
    # def filter_luni(self, indices: list[int]) -> LahutaCPP: ...
    def find_neighbors(self, radius: float, res_diff: int) -> Any: ...
    def find_ring_neighbors(self, radius: float, res_diff: int) -> Any: ...
    # def find_neighbors(self, radius: float, res_diff: int) -> AtomAtomNeighbors: ...
    # def find_ring_neighbors(self, radius: float, res_diff: int) -> AtomRingNeighbors: ...
    def get_atom_types(self) -> list[AtomType]: ...
    def get_cutoff(self) -> float: ...
    def get_rings(self) -> RingDataVec: ...
    # def n_atoms(self) -> int: ...
    def parse_expression(self, expression: str) -> bool: ...
    # def get_indices(self) -> NDArray[np.int32]: ...
    def get_indices(self) -> list[int]: ...
    def get_atomic_numbers(self) -> list[int]: ...
    def get_elements(self) -> list[str]: ...
    def get_symbols(self) -> list[str]: ...
    def get_names(self) -> list[str]: ...
    def get_resids(self) -> list[int]: ...
    def get_resindices(self) -> list[int]: ...
    def get_resnames(self) -> list[str]: ...
    def get_chainlabels(self) -> list[str]: ...
    @staticmethod
    def factorize(labels: list[str] | NDArray[np.str_]) -> list[int] | NDArray[np.int32]: ...
    @overload
    @staticmethod
    def count_unique(labels: list[str] | NDArray[np.str_]) -> int: ...
    @overload
    @staticmethod
    def count_unique(labels: list[int] | NDArray[np.int32]) -> int: ...
    @property
    def file_name(self) -> str: ...
    @property
    def n_atoms(self) -> int: ...
    @property
    def indices(self) -> NDArray[np.int32]: ...
    @property
    def atomic_numbers(self) -> NDArray[np.int32]: ...
    @property
    def elements(self) -> NDArray[np.str_]: ...
    @property
    def names(self) -> NDArray[np.str_]: ...
    @property
    def resids(self) -> NDArray[np.int32]: ...
    @property
    def resindices(self) -> NDArray[np.int32]: ...
    @property
    def resnames(self) -> NDArray[np.str_]: ...
    @property
    def symbols(self) -> NDArray[np.str_]: ...
    @property
    def chainlabels(self) -> NDArray[np.int32]: ...
    @property
    def positions(self) -> NDArray[np.float32]: ...

# FIX: point is a coordinate point; the typing should reflect that
class RingData:
    atom_ids: list[int]
    def __init__(self) -> None: ...
    def compute_angle(self, point: list[float]) -> float: ...
    @property
    def center(self) -> NDArray[np.floating]: ...
    @property
    def norm(self) -> NDArray[np.floating]: ...

class RingDataVec:
    rings: list[RingData]
    def __init__(self) -> None: ...
    def compute_angles(self, ring_indices: list[int], points: list[list[float]]) -> list[float]: ...
    def root_atom_ids(self) -> list[int]: ...
    @property
    def centers(self) -> NDArray[np.floating]: ...
    @property
    def norm(self) -> NDArray[np.floating]: ...

# fmt: off
class AtomType:
    NONE: ClassVar[AtomType]                # value = <AtomType.NONE: 0>
    HBOND_ACCEPTOR: ClassVar[AtomType]      # value = <AtomType.HBOND_ACCEPTOR: 1>
    HBOND_DONOR: ClassVar[AtomType]         # value = <AtomType.HBOND_DONOR: 2>
    WEAK_HBOND_ACCEPTOR: ClassVar[AtomType] # value = <AtomType.WEAK_HBOND_ACCEPTOR: 4>
    WEAK_HBOND_DONOR: ClassVar[AtomType]    # value = <AtomType.WEAK_HBOND_DONOR: 8>
    POS_IONISABLE: ClassVar[AtomType]       # value = <AtomType.POS_IONISABLE: 16>
    NEG_IONISABLE: ClassVar[AtomType]       # value = <AtomType.NEG_IONISABLE: 32>
    CARBONYL_OXYGEN: ClassVar[AtomType]     # value = <AtomType.CARBONYL_OXYGEN: 64>
    CARBONYL_CARBON: ClassVar[AtomType]     # value = <AtomType.CARBONYL_CARBON: 128>
    AROMATIC: ClassVar[AtomType]            # value = <AtomType.AROMATIC: 256>
    HYDROPHOBIC: ClassVar[AtomType]         # value = <AtomType.HYDROPHOBIC: 512>
    XBOND_ACCEPTOR: ClassVar[AtomType]      # value = <AtomType.XBOND_ACCEPTOR: 1024>
    XBOND_DONOR: ClassVar[AtomType]         # value = <AtomType.XBOND_DONOR: 2048>
    INVALID: ClassVar[AtomType]             # value = <AtomType.INVALID: 4096>

    def __init__(self, value: int) -> None: ...

    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __invert__(self) -> Self: ...

    def __and__(self, other: Self) -> Self: ...
    def __iand__(self, other: Self) -> Self: ...
    def __or__(self, other: Self) -> Self: ...
    def __ior__(self, other: Self) -> Self: ...
    def __xor__(self, other: Self) -> Self: ...
    def __ixor__(self, other: Self) -> Self: ...

    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

    def __getstate__(self) -> int: ...
    def __setstate__(self, state: int) -> None: ...

    def has(self, other: Self) -> bool: ...
    def all(self, other: Self) -> bool: ...
    def any(self, other: Self) -> bool: ...
    def none(self, other: Self) -> bool: ...
    def empty(self) -> bool: ...
    def components(self) -> list[Self]: ...
    def has_enum_as_str(self, name: str) -> bool: ...
    def get_enum_as_str(self) -> str: ...
    def print_flags(self) -> list[Self]: ...

    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...

# fmt: on
def factorize_residues(
    resnames: Labels, resids: Indices, chainlabels: Labels
) -> tuple[list[int], list[str], list[int], list[str]]: ...
