from collections.abc import Sequence
from dataclasses import dataclass
from enum import Enum
from typing import (
    Any,
    Callable,
    ClassVar,
    Generic,
    Iterable,
    Iterator,
    NewType,
    Protocol,
    Self,
    TypeAlias,
    TypeVar,
    overload,
)

import numpy as np
from numpy.typing import NDArray

from lahuta.lib._contacts import Contact as Contact
from lahuta.lib._contacts import Contacts as Contacts
from lahuta.lib._contacts import EntityID as EntityID
from lahuta.lib._contacts import EntityType as EntityType
from lahuta.lib._contacts import InteractionOptions as InteractionOptions
from lahuta.lib._contacts import Interactions as Interactions
from lahuta.lib._contacts import InteractionType as InteractionType
from lahuta.lib._entities import AtomEntity as AtomEntity
from lahuta.lib._entities import AtomEntityCollection as AtomEntityCollection
from lahuta.lib._entities import EntityNeighborSearch as EntityNeighborSearch
from lahuta.lib._entities import GroupEntity as GroupEntity
from lahuta.lib._entities import GroupEntityCollection as GroupEntityCollection
from lahuta.lib._entities import RingEntity as RingEntity
from lahuta.lib._entities import RingEntityCollection as RingEntityCollection

# from lahuta.lib import atom_types as atom_types
# from lahuta.lib.atom_types import AtomType as AtomType

# from lahuta.lib._lahuta.atom_types import AtomType

# __all__ = ["CCAtomType"]

# fmt: off

# NOTE: it would be nice to simplify the typing by encapsulating the `list`
# and `NDArray` types in a custom type alias or protocol, but type checkers
# do not expand these, so the user is left wondering what StrIter is.
# class StrIter(Protocol):
#     def __iter__(self) -> Iterator[str]: ...
# StrIter: TypeAlias = list[str] | NDArray[np.str_]

Labels:  TypeAlias = list[str] | NDArray[np.str_]
Indices: TypeAlias = list[int] | NDArray[np.int32]

Vector: TypeAlias = NDArray[np.float64] # shape=(3,)
Matrix: TypeAlias = NDArray[np.float64] # shape=(n_atoms, 3)
# Vector = NewType("Vector", NDArray[np.float64])
# Matrix = NewType("Matrix", NDArray[np.float64])


_Float_co = TypeVar("_Float_co", bound=np.floating[Any], covariant=True)
VectorType: TypeAlias = NDArray[_Float_co]  # shape=(3,)
MatrixType: TypeAlias = NDArray[_Float_co]  # shape=(n_atoms, 3)

class Atom:
    @property
    def atomic_number(self) -> int: ...
    @property
    def symbol(self) -> str: ...
    @property
    def idx(self) -> int: ...
    @property
    def degree(self) -> int: ...
    @property
    def formal_charge(self) -> int: ...
    @property
    def hybridization(self) -> int: ...
    @property
    def num_explicit_Hs(self) -> int: ...
    @property
    def num_implicit_Hs(self) -> int: ...
    @property
    def total_num_Hs(self) -> int: ...
    @property
    def total_valence(self) -> int: ...
    @property
    def explicit_valence(self) -> int: ...
    @property
    def implicit_valence(self) -> int: ...
    @property
    def is_aromatic(self) -> bool: ...
    @property
    def mass(self) -> float: ...


class Point3D:
    x: float
    y: float
    z: float
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0) -> None: ...



class NSResults_:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, pairs: list[tuple[int, int]], distances: list[float]) -> None: ...
    @overload
    def __init__(self, pairs: NDArray[np.int32], distances: NDArray[np.float32]) -> None: ...
    def add(self) -> None: ...
    def add_neighbors(self) -> None: ...
    def reserve_space(self) -> None: ...
    def size(self) -> int: ...
    def clear(self) -> None: ...
    def get_pairs(self) -> NDArray[np.int32]: ...
    def get_distances(self) -> NDArray[np.float32]: ...
    @overload
    def filter(self, value: float) -> NSResults_: ...
    @overload
    def filter(self, indices: list[int]) -> NSResults_: ... # replace list[int] with AtomIndices or something
    @overload
    def filter(self, indices: list[int], column_idx: int) -> NSResults_: ... # replace list[int] with AtomIndices or something


class FastNS_:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, coords: NDArray[np.float64] | None, scale_factor: float | None = 1.1) -> None: ...
    @overload
    def __init__(self, coords: list[list[float]] | None, scale_factor: float | None = 1.1) -> None: ...

    def build(self, cutoff: float) -> bool: ...
    def update(self, cutoff: float) -> bool: ...
    def adaptive_build(self, cutoff: float, max_retries: int = 50) -> bool: ...
    def self_search(self) -> NSResults_: ...
    def search(self, search_coords: list[Point3D]) -> NSResults_: ...
    def get_cutoff(self) -> float: ...
    @staticmethod
    def dist_sq(a: Sequence[float], b: Sequence[float]) -> float: ...


class DistanceComputation_:
    @overload
    @staticmethod
    def distance(a: MatrixType[_Float_co])     -> MatrixType[_Float_co]: ...

    @overload
    @staticmethod
    def distance(a: Sequence[Sequence[float]]) -> MatrixType[_Float_co]: ...

    @overload
    @staticmethod
    def distance(a: Sequence[float],           b: Sequence[float]) -> float: ...

    @overload
    @staticmethod
    def distance(a: MatrixType[_Float_co],     b: MatrixType[_Float_co])         -> MatrixType[_Float_co]: ...

    @overload
    @staticmethod
    def distance(a: Sequence[Sequence[float]], b: Sequence[Sequence[float]]) -> MatrixType[_Float_co]: ...

    @overload
    @staticmethod
    def search(a: MatrixType[_Float_co],         cutoff: float) -> NSResults_: ...

    @overload
    @staticmethod
    def search(a: Sequence[Sequence[float]], cutoff: float) -> NSResults_: ...

    @overload
    @staticmethod
    def search(a: MatrixType[_Float_co],         b: MatrixType[_Float_co],         cutoff: float) -> NSResults_: ...

    @overload
    @staticmethod
    def search(a: Sequence[Sequence[float]], b: Sequence[Sequence[float]], cutoff: float) -> NSResults_: ...



# Intermediate Representation
@dataclass
class IR:
    atom_indices: list[int] | NDArray[np.int32]
    atom_nums:    list[int] | NDArray[np.int32]
    resids:       list[int] | NDArray[np.int32]
    atom_names:   list[str] | NDArray[np.str_]
    resnames:     list[str] | NDArray[np.str_]
    chainlabels:  list[str] | NDArray[np.str_]
    positions:    NDArray[np.float32]

class Residue:
    chain_id: str
    number:   int
    name:     str
    alt_loc:  str
    atoms:    list[int]


_T = TypeVar("_T")
class Residues_:
    @property
    def residues(self) -> list[Residue]: ...
    def residue_map(self)  -> dict[int, list[Residue]]: ...
    def filter(self, func: Callable[[Residue], bool]) -> Residues_: ...
    def map(self,    func: Callable[[Residue], _T])   -> list[_T]: ...
    def __iter__(self) -> Iterator[Residue]: ...
    def __getitem__(self, index: int) -> Residue: ...


class ContactComputerType(Enum):
    None_    = 0
    Arpeggio = 1
    Molstar  = 2


@dataclass
class TopologyBuildingOptions:
    bonded_search_cutoff: float = 4.5 # the maximum distance to search for bonded atoms
    atom_typing_method: ContactComputerType = ContactComputerType.Molstar


@dataclass
class Topology_:
    @property
    def residues(self)   -> Residues_: ...
    @property
    def rings(self)      -> RingEntityCollection: ...
    @property
    def atom_types(self) -> AtomEntityCollection: ...
    # TODO: indexing by integer should give an atom object
    # TODO: indexing by list | slice should give a list of atom objects


# TODO: main lahuta class should support creating an MDAnalysis object
# TODO: MDAnalysis installation should maybe be optional? (not sure)
class LahutaCPP:
    # @overload
    # def __init__(self) -> None: ...
    @overload
    def __init__(self, filename: str, contact_type: int = 1) -> None: ...
    @overload
    def __init__(self, ir: IR) -> None: ...
    def build_topology(self, t_ops: TopologyBuildingOptions | None = None) -> bool: ...
    # def get_positions(self) -> list[list[float]]: ...
    def get_positions(self, conformer_index: int = -1) -> NDArray[np.float64]: ...
    # def filter(self) -> LahutaCPP: ...
    # def filter_luni(self, indices: list[int]) -> LahutaCPP: ...
    def find_neighbors(self, radius: float, res_diff: int) -> Any: ...
    def find_ring_neighbors(self, radius: float, res_diff: int) -> Any: ...
    # def find_neighbors(self, radius: float, res_diff: int) -> AtomAtomNeighbors: ...
    # def find_ring_neighbors(self, radius: float, res_diff: int) -> AtomRingNeighbors: ...
    def get_atom_types(self) -> list[AtomType]: ...
    def get_cutoff(self) -> float: ...
    def get_rings(self) -> RingEntityCollection: ...
    # def n_atoms(self) -> int: ...
    def parse_expression(self, expression: str) -> bool: ...
    # def get_indices(self) -> NDArray[np.int32]: ...
    def get_indices(self) -> list[int]: ...
    def get_atomic_numbers(self) -> list[int]: ...
    def get_elements(self) -> list[str]: ...
    def get_symbols(self) -> list[str]: ...
    def get_names(self) -> list[str]: ...
    def get_resids(self) -> list[int]: ...
    def get_resindices(self) -> list[int]: ...
    def get_resnames(self) -> list[str]: ...
    def get_chainlabels(self) -> list[str]: ...

    def get_atom(self, index: int) -> Atom: ...

    def get_topology(self) -> Topology_: ...
    @staticmethod
    def factorize(labels: list[str] | NDArray[np.str_]) -> list[int] | NDArray[np.int32]: ...
    @overload
    @staticmethod
    def count_unique(labels: list[str] | NDArray[np.str_]) -> int: ...
    @overload
    @staticmethod
    def count_unique(labels: list[int] | NDArray[np.int32]) -> int: ...

    # FIX: this actually returns a list of strings
    @staticmethod
    def find_elements(atomic_numbers: list[int] | NDArray[np.int32]) -> NDArray[np.str_]: ...
    @property
    def file_name(self) -> str: ...
    @property
    def n_atoms(self) -> int: ...
    @property
    def indices(self) -> NDArray[np.int32]: ...
    @property
    def atom_nums(self) -> NDArray[np.int32]: ...
    @property
    def elements(self) -> NDArray[np.str_]: ...
    @property
    def names(self) -> NDArray[np.str_]: ...
    @property
    def resids(self) -> NDArray[np.int32]: ...
    @property
    def resindices(self) -> NDArray[np.int32]: ...
    @property
    def resnames(self) -> NDArray[np.str_]: ...
    @property
    def symbols(self) -> NDArray[np.str_]: ...
    @property
    def chainlabels(self) -> NDArray[np.int32]: ...
    @property
    def positions(self) -> NDArray[np.float64]: ...


# FIX: point is a coordinate point; the typing should reflect that
class RingData:
    # atom_ids: list[int]
    def __init__(self) -> None: ...
    # def compute_angle(self, point: list[float]) -> float: ...
    def atom_ids(self) -> list[int]: ...
    @property
    def center(self) -> NDArray[np.floating]: ...
    @property
    def norm(self) -> NDArray[np.floating]: ...


class AtomType(Enum): # FIX: write the actual values
    NONE:                AtomType # 0
    HBOND_ACCEPTOR:      AtomType # 1
    HBOND_DONOR:         AtomType # 2
    WEAK_HBOND_ACCEPTOR: AtomType # 4
    WEAK_HBOND_DONOR:    AtomType # 8
    POS_IONISABLE:       AtomType # 16
    NEG_IONISABLE:       AtomType # 32
    CARBONYL_OXYGEN:     AtomType # 64
    CARBONYL_CARBON:     AtomType # 128
    AROMATIC:            AtomType # 256
    HYDROPHOBIC:         AtomType # 512
    XBOND_ACCEPTOR:      AtomType # 1024
    XBOND_DONOR:         AtomType # 2048
    INVALID:             AtomType # 4096

    def __init__(self, value: int) -> None: ...

    def split(self) -> list[Self]: ...

    @property
    def value(self) -> str: ...

    def __index__ (self) -> int: ...
    def __int__   (self) -> int: ...
    def __hash__  (self) -> int: ...
    def __invert__(self) -> Self: ...

    def __and__(self, other: Self) -> Self: ...
    def __or__(self,  other: Self) -> Self: ...
    def __xor__(self, other: Self) -> Self: ...
    def __iand__(self, other: Self) -> Self: ...
    def __ior__(self,  other: Self) -> Self: ...
    def __ixor__(self, other: Self) -> Self: ...

    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

    def __getstate__(self) -> int: ...
    def __setstate__(self, state: int) -> None: ...


class Flags:
    @staticmethod
    def has(types: AtomType, has_type: AtomType) -> bool: ...
    @staticmethod
    def has_any(types: AtomType, has_type: AtomType) -> bool: ...
    @staticmethod
    def all(types: AtomType, has_type: AtomType) -> bool: ...
    @staticmethod
    def any(types: AtomType, has_type: AtomType) -> bool: ...
    @staticmethod
    def none(types: AtomType, has_type: AtomType) -> bool: ...
    @staticmethod
    def empty(types: AtomType) -> bool: ...
    @staticmethod
    def split(types: AtomType) -> list[AtomType]: ...
    @staticmethod
    def get_enum_as_string(types: AtomType) -> str: ...
    @staticmethod
    def string_to_atom_type(s: str) -> AtomType: ...


def factorize_residues(resnames: Labels, resids: Indices, chainlabels: Labels) -> tuple[list[int], list[str], list[int], list[str]]: ...


class _EntityInterface(Protocol):
    def get_center(self) -> Point3D: ...
    def get_id(self) -> int: ...


_EI = TypeVar("_EI", bound=_EntityInterface)
class Entity(Generic[_EI]):
    def __init__(self, t: _EI) -> None: ...
    def get_center(self) -> Point3D: ...
    def get_id(self) -> int: ...

class Logger_:
    class LogLevel(Enum):
        Trace    = 0
        Debug    = 1
        Info     = 2
        Warn     = 3
        Error    = 4
        Critical = 5
        Off      = 6

    class FormatStyle(Enum):
        Simple   = 0
        Detailed = 1

    @staticmethod
    def get_instance() -> Logger_: ...

    def set_format(self,    style: FormatStyle) -> None: ...
    def set_log_level(self, level: LogLevel)    -> None: ...

    def log(self, level: LogLevel, message: str) -> None: ...
