name: Test Conda Installation

on:
  release:
    types: [published]

jobs:
  test-conda-install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
          activate-environment: test-env

      - name: Install Library
        shell: bash -l {0}
        run: conda install -c conda-forge -c bisejdiu lahuta

      - name: Test Library Installation
        shell: bash -l {0}
        run: |
          python -c "import lahuta"
          python -c "import unittest; from lahuta.scripts.only_aromatic import SimpleTest; unittest.TextTestRunner().run(unittest.TestLoader().loadTestsFromTestCase(SimpleTest))"
          python -c "import unittest; from lahuta.scripts.fast_contacts import ContactTest; unittest.TextTestRunner().run(unittest.TestLoader().loadTestsFromTestCase(ContactTest))"
